6pac/SlickGrid

- plugins/slick.cellselectionmodel.js
- plugins/slick.rowselectionmodel.js
https://github.com/6pac/SlickGrid/issues/9
> Prevent useless onSelectedRangesChanged events in selectionmodels' setSelectedRanges

- examples/example6-ajax-loading-yahoo.html
> fixed link to example source

- slick.grid.js
- tests/grid/grid.js
Create the scrollColumnIntoView function to go to a column without scrolling rows
> Scroll column into view

- examples/example-draggable-grouping.html
- plugins/slick.draggablegrouping.js
Updated example and added credit comments.
> draggable-grouping

- examples/example-multiselect-editor.html
> Updated source code link

- examples/example-plugin-headermenu.html
- examples/example15-auto-resize.html
- examples/index.html
Referencing to open issue #154 and perhaps related to #31
> add new example: Grid auto-resize on browser resize

- slick.grid.js
Please have a look to my changes.
I needed to be able to handle home/end keys in the grid
> Handle home/end key and the ctrl variants

- slick.dataview.js
Also moved the sorted* functions a bit later in the code and a teensy-weensy bit of formatting.
> Changed signature of sortedUpdateItem() to be the same as updateItem().

- examples/example-grouping.html
- slick.groupitemmetadataprovider.js
Closes #222 
Created a PR as per discussion with @6pac in that issue reference
> feat: closes #222 expose grid in groupitemmetadataprovider

- plugins/slick.draggablegrouping.js
This should fix the issue #299 that I reported and I tested it locally and it now works as I intend it to.
> fixes issue #299, notify onGroupChanged even on empty array

- controls/slick.columnpicker.js
- examples/example-checkbox-header-row.html
Changed the options references to be internal.
This is to fix when there isn't an options at global variable level
This version includes @ghiscoding changes.
> Fix options references

- examples/example17-row-detail-many-columns.html
- plugins/slick.rowdetailview.js
- slick.grid.js
Added a way to always render the columns even when they go out of horizontal bounds.
As discussed in #306. Example is included
Please check and advice about cleanUpAndRenderCells function as mentioned in discussion.
> Added alwaysRenderColumn

- examples/example-checkbox-header-row.html
- plugins/slick.checkboxselectcolumn.js
- we can now override via the options or via the plugin instance
> feat(checkbox): add possibility to override directly from plugin options

- examples/example-select2-editor.html
- examples/example-select2-multiselect-editor.html
This commit fixes following problems in Select2 examples.
- Grid would not scroll after select2 destroyed without closing.
- Hiding select2 by scroll may cause TypeError in console.
See issue #361.
> fix(examples): Select2 examples have some glitches (#361)

- README.md
- lib/jquery.event.drag-2.3.0.js
> Fix to Fix jquery.event.drag suppressing native drag and drop #239

- lib/jquery.event.drag-2.3.0.js
- reference, issue opened in Angular-Slickgrid https://github.com/ghiscoding/Angular-Slickgrid/issues/207
- I see the same behavior in SlickGrid itself, so it is better to rollback the commit and think of another solution
> fix(event): rollback commit 34ec867 to fix column resize is broken

- examples/example-frozen-columns-large.html
- slick.grid.js
> fix(ie): increase performance in IE, closes #367

- controls/slick.columnpicker.js
- controls/slick.gridmenu.js
- add updateAllTitles to both controls ColumnPicker & GridMenu to dynamically change titles on the fly
> feat(controls): add updateAllTitles to controls

- slick.grid.js
triggeredByColumn shows which column triggered the onColumnsResized event
> Add triggeredByColumn to args for onColumnsResized

- slick.dataview.js
Aggregators may not need/want to iterate through all the rows, and thus not use the "accumulate" function. This change checks for the presence of that function, and if it does not exist, then it does not do the iteration. A "CountAggregator" has also been added as a feature, but also to show how/why this is necessary. Other use cases are "count distinct" or perhaps aggregations are already done and stored elsewhere for quick use.
> Make aggregators "accumulate" function optional

- slick.grid.js
Add events for onFooterClick and onFooterContextMenu
> Footer Click and Context Menu Events

- controls/slick.gridmenu.js
> fix(gridMenu): menu at wrong place when using Frozen Col 0, fixes #436

- slick.grid.js
> (element): make sure DOM element exist before using it, fixes #398

- examples/example15-auto-resize.html
- plugins/slick.resizer.js
This plugin is mostly for handling auto-resize, but user can also optionally pass fixed dimensions. 
I'm not sure how to test window size in Cypress, so I won't make any E2E tests for this plugin, however I tested it all manually.
> feat(plugin): create a new Resizer plugin for easier auto-resize

- cypress/integration/example-plugin-headermenu.spec.js
- package-lock.json
- package.json
fixes #471 
After running a local `npm install`, I get the following, so I assume it's all good
```shell
found 0 vulnerabilities
```
> fix(npm): update Cypress to fix security warnings, fixes #471

- .gitignore
- .npmignore
> fix(npm): remove certain files from npm, closes #499

- plugins/slick.resizer.js
> fix(resizer): check for undefined option instead of fallback, fix #504

- examples/example2-formatters.html
The previous one will always be 'true'.
> Fixing condition in the formatter body

- .github/workflows/main.yml
- .vscode/tasks.json
- README.md
- cypress/integration/example-plugin-headermenu.spec.js
- package-lock.json
- package.json
- slick.dataview.js
- updated few npm packages
- updated GitHub Actions packages as well
- add `getItemsCount` function into DataView to avoid having to use `getData().length` anytime we want to know the data length
> feat: add getItemsCount function to DataView & update few npm packages

- controls/slick.gridmenu.js
- cypress/integration/example-grid-menu.spec.js
- examples/example-grid-menu.html
- package-lock.json
- package.json
- fix regression issue found from last PR #615
- add demo code and Cypress E2E tests to cover the regression bug
- use gridmenu hidden css class instead of incorrect headermenu hidden class
- update Cypress to latest version
> fix: Grid Menu grid options should be passed by reference

- plugins/slick.customtooltip.js
- there's really no need to show tooltip with empty text
> fix: avoid showing empty text tooltip

- slick.grid.js
- to go with previous PR #652 that I added recently and in some circumstance the user might want to provide his own sanitizer.
Here's a JS Bin test for this optional grid option
> feat: add grid option to provide optional sanitizer function

- slick.grid.js
> #681 Fix scroll position after updateRowCount()

- slick.grid.js
Correct incorrect reference to viewport which results in incorrect scrollbar width calculation
> fix getScrollBarWidth bug

- examples/example-plugin-custom-tooltip.html
- plugins/slick.customtooltip.css
- plugins/slick.customtooltip.js
- add new "center" position option
- custom alignment of tooltip were inverted to the user's expectation, this PR fixes that
> feat(tooltip): add new "center" and invert left/right align

- .github/workflows/main.yml
- plugins/slick.cellrangeselector.js
> fix: cell selection in Firefox not working, fixes #714

- .github/workflows/main.yml
- update a few GitHub Actions plugins to their latest versions
> chore: update GitHub Actions to use latest versions

- slick.grid.js
- fixes #735
- ref: SortableJS [AutoScroll](https://github.com/SortableJS/Sortable/tree/master/plugins/AutoScroll) feature
> fix: enable AutoScroll with SortableJS for column reordering, fixes #735

- .eslintrc
- examples/example-external-headersort.html
- package-lock.json
- package.json
- plugins/slick.draggablegrouping.js
- slick.core.js
- slick.grid.js
- fix ESLint for Cypress
- also remove jQuery from `package.json` list of dependencies
> feat(plugins): convert slick.draggablegrouping to vanillaJS

- cypress/integration/example-grid-menu.spec.js
- examples/example-grid-menu.html
- slick.grid.js
- slick.interactions.js
- also remove `passive` mode to certain events that use `preventDefault` since that is not compatible with `passive` mode
> chore: better use of DOM element creation and innerHTML

- examples/example-grid-menu-slim-style.html
- examples/example-plugin-contextmenu-slim-style.html
- examples/example-slim-style.css
- examples/example3-editing-slim-style.html
- examples/example4-model-slim-style.html
- the theme was copied from [vue-slimgrid](https://github.com/rob-white/vue-slimgrid#examplevue) project and adjusted a bit, not perfect but provides a bit more modern styling theme
- I just copied 3 examples and renamed them so that we can link them in the Wiki list of Examples
below are some print screens showing the differences (left/right)
> feat: provide another styling theme

- plugins/slick.autotooltips.js
- plugins/slick.headermenu.js
- small issues found after converting some plugins to vanilla JS
> fix: remove invalid TS type and invalid this object

- examples/example-composite-editor-modal-dialog.html
> fix(demo): calling cancel or close button should close modal

- src/slick.grid.ts
Added the same change in next branch
> Viewport height fix

- examples/example-grouping-esm.html
- examples/example-trading-esm.html
- examples/example4-model-esm.html
- examples/index.html
> feat: add new trading platform high frequency update grid

- .gitignore
- .vscode/launch.json
- add VSCode debugger config, to provide troubleshooting with breakpoints as shown below
> chore: add VSCode debugger config

- examples/example-drag-row-between-grids.html
- examples/example-frozen-row-reordering.html
- examples/example9-row-reordering-simple.html
- examples/example9-row-reordering.html
- src/models/rowMoveManagerOption.interface.ts
- src/plugins/slick.crossgridrowmovemanager.ts
- src/plugins/slick.rowmovemanager.ts
- this basically rolls back PR #865 that caused the regression
> fix: regression with RowMoveManager, row could no longer be moved

- slick.grid.js
- backported to version 4.x from PR #901
> fix: misaligned column headers after horizontal scroll then freeze

- cypress/e2e/example-example1-simple.cy.ts
- src/slick.grid.ts
- this PR is mostly reverting commit 113b613 which caused a regression as shown in issue #914, we'll have to investigate on how to reapply the change in the future without regressing
- add Cypress E2E tests covering the regression shown in issue #914
> fix: rollback portion of CSP safe code causing regression, fixes #914

- src/slick.grid.ts
This is not ready to get merged, its just to have a place to discuss for now
> fix: change dynamic html string w/CSP safe code to fix scroll, fix #914

- src/plugins/slick.checkboxselectcolumn.ts
- src/plugins/slick.rowselectionmodel.ts
- src/slick.core.ts
- src/slick.dataview.ts
- src/slick.grid.ts
- as per this article [Measuring Performance of Different JavaScript Loop Types](https://blog.bitsrc.io/measuring-performance-of-different-javascript-loop-types-c0e9b1d193ed), the `for...in` and `for...of` aren't the most optimized for loops, the `for` and `.forEach` are more the most optimized methods across all browser engine and the `for...in` seems to be the worst to use and should be avoided when dealing with large dataset which can often be the case with this project
> perf: prefer `.forEach` over `for...in` and `for...of`

- cypress/e2e/example4-model-esm.cy.ts
- examples/example4-model-esm.html
- related to comments in issue #992
> chore: demo `onBeforeEditCell` returning false

- src/models/editor.interface.ts
EditorArguments must never be null
> make Editorarguments required EditorConstructor

- cypress/e2e/example-infinite-scroll-esm.cy.ts
- examples/example-infinite-scroll-esm.html
- examples/index.html
- src/slick.grid.ts
> feat: add new Infinite Scroll example

- src/slick.grid.ts
Performance optimisation from O(n square) to O(n)
> perf: Optimize SlickGrid handleSelectedRangesChanged by using Set

- package-lock.json
- package.json
- src/styles/_variables.scss
- another deprecation from SASS which is again displaying a load of console warnings
- more info on SASS website: https://sass-lang.com/documentation/breaking-changes/color-functions/
> fix: SASS deprecated `lighten` and `darken` methods

- src/slick.grid.ts
> fix: shift+mousewheel should scroll horizontally, fixes #1094

- src/slick.grid.ts
- Extracted related logic into contextual groups
- Goal to help improve maintainability and readability (~7000 lines)
- No functional changes were made
- Existing behaviour, test results and performance remain unchanged.
This PR refactors the `slick.grid.ts` module by grouping related logic into contextual function groups. The goal is to help improve maintainability and codebase intuition.
- Extracted related logic into function groups to improve clarity and maintainability.
- No functional changes were introduced.
- Existing behaviour, test results, and performance remain unchanged.
The module had grown to ~7000 lines, making it difficult to navigate and follow. This refactor aims to enhance code structure while preserving all existing functionality. Grouping similar functions together …
> refactor: Refactored slick.grid.ts module into function groups.

- src/slick.grid.ts
- also remove all extra unnecessary whitespaces
> chore: fix all linting & indentation problems

- examples/example4-model-esm.html
- src/slick.grid.ts
- refactor from code that comes from previously closed PR #1108, that previous PR was closed but the code refactoring does make sense since it's good way to remove duplicate code
> refactor: externalize duplicate code into separate function

- src/slick.grid.ts
- trigger an event before the row gets removed from  the cache, this can be useful for plugin like the Row Detail
> feat: add `onBeforeRemoveCachedRow` SlickGrid event

- src/slick.grid.ts
- depending on which `border-sizing` style the user has defined on its grid container element, the border was sometime not showing at bottom of the grid (ie: the grid below should have a border all around, but its bottom border wasn't showing)
- this wasn't an issue if the container has `border-sizing: 'content-box'` but most users have it set to `'border-box'` which is the default.
- this problem existed since as long as I can remember and this PR should finally fix it :)
> fix: incorrect grid container box size calculation border not showing

- src/plugins/slick.rowdetailview.ts
This is an attempt to address the issue described here:
fix #654
> fix: small fix in Row Detail plugin to make it work with Grouping
