6pac/SlickGrid

slick.grid.js
After I tried to monkey patch jquery draggable into slickgrid it seemed to work pretty well. In case people have  problems with jquery.event.drag.js (as I did), this will remove that dependency within the core grid.
=> Changed all drag events to draggable handles

slick.grid.js
It seems an obvious boundary check mistake, comparing the 2 condition check in https://github.com/6pac/SlickGrid/blob/2.1/slick.grid.js#L1601-L1610.
=> fix bug - do not remove last row from cache

controls/slick.columnpicker.js, examples/example-header-row.html, examples/example3a-compound-editors.html, examples/example9-row-reordering.html, plugins/slick.headerbuttons.js, plugins/slick.headermenu.js, slick.editors.js, slick.grid.js
Hey @6pac, thanks for your work in keeping this.
This PR is a set of harmless changes in order to provide compatibility with jQuery 3.
The changes were based on running the jQuery Migration plugin for version 3. They are supposed to be harmless and were doubled checked by running the tests (nothing broke) and also did some basic manual testing.
For more details on each change see:
- https://jquery.com/upgrade-guide/3.0/
And more specifically:
- https://github.com/jquery/jquery-migrate/blob/master/warnings.md#jqmigrate-jqueryfnandself-replaced-by-jqueryfnaddback
- https://github.com/jquery/jquery-migrate/blob/master/warnings.md#jqmigrate-jqueryfnbind-is-deprecated
I also removed trailing whitespace, so feel free to [view the diff without whitespace …
=> Changes to support jQuery 3

lib/jquery.event.drag-2.2.js, lib/jquery.event.drop-2.2.js
**NOTE**: please use the [`?w=1` option](https://github.com/6pac/SlickGrid/pull/44/files?w=1) to see the diff - lots of whitespace change (mixed and wrong indentation)
This removes the fixHooks part (supported by jq3 now) and updates the code to be jq3 compatible.
=> Update event drag lib to be jQ 3 compatible

controls/slick.columnpicker.js
Added a scroll on Y overflow to the column picker. Useful with large quantity of columns when not all column fit into the browser window.
=> Scroll on Y overflow when using column picker

controls/slick.columnpicker.js, slick.dataview.js
Added the possibility to use HTML for the column picker labels.
Today, it is possible to use html for header labels within SlickGrid however the column picker doesn't support it. The result is an ugly html tag with content instead of a nicely formatted DOM.
This commit/pull request allows to have header labels as html while using the column picker.
=> Allow html for columnpicker labels

examples/example-excel-compatible-spreadsheet.html, plugins/slick.cellexternalcopymanager.js
I think this is a common use-case: copy a chunk of data from Excel then paste into an empty SlickGrid. It's a pain to have to insert the appropriate number of blank rows beforehand.
=> Add support for adding extra rows at bottom if paste overflows

plugins/slick.cellexternalcopymanager.js
If you copy something from the SlickGrid by shortcut key, you can't then use the cursor keys to navigate afterwards. It seems to me that the old code to restore the focused component never worked?
=> Fix bug where can't navigate by cursor keys after paste

slick.dataview.js
* This allows using the original default filter in a custom filter
* Means I dont have to rewrite the full default filter to add a new
addition
* Should allow multiple passes of replacing a filter with one that
extends the previous one.
=> Allow retrieval of the default filter on a dataView

plugins/slick.cellselectionmodel.js, tests/plugins/cellselectionmodel.html, tests/plugins/cellselectionmodel_spec.js
When using the Control Key + Arrow Key the plugin ensures that there are no changes to the selections ranges. 
For Mac the combination Command Key + Arrow Key should have the same behavior.
Add some tests to the plugin to ensure it is working as expected.
=> Cell Selection Model plugin allow Mac Command key + arrows to change the selection

plugins/slick.cellrangeselector.js, tests/plugins/cellrangeselector.html, tests/plugins/cellrangeselector_spec.js
- so we can access the range during a drag
- this is useful when e.g. the mouse left the #grid before a mouseup
=> Add getCurrentRange() to CellRangeSelector

plugins/slick.cellrangeselector.js, plugins/slick.cellselectionmodel.js, tests/plugins/cellrangeselector_spec.js
Allow dependency injection on CellSelectionModel, by receiving via options a instance of CellRangeSelector. Kept backward compatibility by ensuring the object is created if not provided
=> Remove variable from global status

slick.dataview.js
They allow for very high performance when the data changes a lot.
Data must be initially sorted (the regular way: `dataView.sort(comparer)`), then items can be added, updated and removed without continuous sorting, which is otherwise required.
=> Added functions sortedAddItem() and sortedUpdateItem() to DataView

plugins/slick.cellrangedecorator.js, plugins/slick.cellrangeselector.js, plugins/slick.cellselectionmodel.js, tests/plugins/cellrangedecorator.html, tests/plugins/cellrangedecorator_spec.js, tests/plugins/cellrangeselector_spec.js
Mainly the right and bottom bounds seemed misaligned from the column and row gridlines.
**We were seeing:**
**our changes leave us with:**
Please try the modified cellrangedecorator and let us know if it looks good.
=> Change selection box boundary

slick.grid.js
I don't know if I'm doing something wrong but I'm getting the following error:
```
slick.grid.js:1844 Uncaught TypeError: cellNode.addClass is not a function
at applyFormatResultToCellNode (slick.grid.js:1844)
at makeActiveCellNormal (slick.grid.js:2979)
at Object.commitCurrentEdit (slick.grid.js:3632)
at EditorLock.commitCurrentEdit (slick.core.js:476)
at commitEditAndSetFocus (slick.grid.js:3054)
at HTMLDivElement.handleKeyDown (slick.grid.js:2637)
at HTMLDivElement.dispatch (jquery-1.11.2.min.js:3)
at HTMLDivElement.i.dispatch (jquery.event.drag.min.js:6)
at HTMLDivElement.r.handle (jquery-1.11.2.min.js:3)
```
`removeClass` and `addClass` are Jquery functions and they were being called on a raw html element
I've just wrapped `cellNode` into the corresponding `$()`
=> Bugfix on applyFormatResultToCellNode()

slick.grid.js
Fix a bug where sometimes when resizing a column header, after dragging ends the column header would receive a click event and sort the column.
see https://github.com/6pac/SlickGrid/issues/141
=> Fix column click/sort after resize

slick.grid.css, slick.grid.js
• Adding a scroll handler for the headerScroller
• Adjusting header css to overflow: auto in order to be scrollable
• cleanup scroll handler functions
• cleanup inlline css -> slick.grid.css
See https://github.com/6pac/SlickGrid/issues/136
=> Fix for Issue #136: Horizontal scrolling of header does not work:

slick.grid.js
This PR does a few things:
- fix the code in `measureScrollbar()` which was broken (always returned 0 on latest chrome). I replaced it with code from the Google Closure Library (see https://stackoverflow.com/a/21046991/460084), the new code creates an outer element and places a bigger inner elements and then calculate the scrollbar dimentions.
- added options.viewportClass to allow styling the viewport. This allows changing the scrollbar appearance (in chrome & IE) for example:
```
.visibleScrollbar::-webkit-scrollbar {
width: 14px;
background-color: #F5F5F5;
border-left: 1px dotted silver;
}
.visibleScrollbar::-webkit-scrollbar-thumb {
background: #D3D3D3;
border: 2px solid #F5F5F5;
border-radius: 0px;
}
.invisibleScrollbar::-webkit-scrollbar {
display: none;
} …
```
=> Fix scrollbar width calculation

examples/example15-auto-resize.html, examples/index.html
Recreated the auto-resize functionality that I mistakenly removed by mistake in another PR.
This PR is related to #154 and brings the functionality of Grid Auto-Resize when Browser Size changes
=> add new example: Grid auto-resize on browser resize

controls/slick.gridmenu.css, controls/slick.gridmenu.js, examples/example-grid-menu.html
This a totally new Slick Control to add a Grid Menu (aka hamburger menu on top-right of the grid). This is based on a previous PR #159 (column picker) and also re-used some code and concept from the Header Menu Plugin. 
What does it do?
- Add a fixed/sticky Grid Menu on top-right of the grid
- Possibility to attach the Grid Menu to an external button 
- Possibility to add custom menu items via a simple array provided to the grid options (same concept as the header menu plugin)
- Once defined, just subscribe to the `onCommand`
- Includes column picker in the grid menu (Column Picker Control is **not** required for this to work, since I copied over the necessary code to produce the column picker).
- Optional title for the custom menu items (top section)
- Optional title for the columns list …
=> Add new Slick Control Grid Menu (hamburger menu)

controls/slick.columnpicker.css, controls/slick.columnpicker.js, examples/example4-model.html
This PR brings the following functionalities
- Added a new grid option `columnPickerTitle` to provide an **optional** title
- in the example shown below, I used: `var options = { columnPickerTitle: "Columns" }`
- Added a close (x) button shown on top right (floating right)
- Hiding the picker is now much more user friendly
- Picker now ONLY hides if user clicks outside of the picker OR clicks on the new close button
- Removed `onMouseLeave` which used to hides the picker as soon as user mouses away from the picker (which was not very user friendly).
- Also added css `resize: both` so that user can choose to expand picker `div` (x, y)
See animated gif for before and after
BEFORE
**AFTER**
_now the picker stays open unless user **clicks outside** of the picker **or** on the new **close …
=> made column picker more functional

slick.grid.css, slick.grid.js
Also corrects misplaced border on default theme / other themes. This related to issue 162, which was closed without really addressing the issue on Firefox. I didn't notice any breaks in other examples and it does solve the issues in Example 11 on IE11/Firefox/Chrome/Edge.
=> Fix for column header width during autoHeight

examples/example-checkbox-row-select.html, plugins/slick.checkboxselectcolumn.js
This PR simply adds an empty `<label>` to each checkbox selector. What does that bring to the table? We can apply extra styling that is not possible without a `<label>`. For example, I want to replace the checkbox (that is different in every browser) by a Font-Awesome [icon](http://fontawesome.io/icon/check/) that will be consistent in all browser and since it's a Font, I can choose whichever size or color I want and it will be consistent across all browser. 
The PR changes the Formatter of the input checkbox from this
```javascript
"<input type='checkbox' checked='checked'>"
```
To this
```javascript
"<input id='selector" + row + "' type='checkbox' checked='checked'><label for='selector" + row + "'></label>"
```
It's really just adding a `<label>` to the input
=> add empty label on checkbox selector for styling purposes

controls/slick.columnpicker.js, controls/slick.gridmenu.js, examples/example4-model.html
As the title says, it brings customization of certain text titles for i18n purposes. There are 2 controls affected by this PR (ColumnPicker and GridMenu). They both had fixed English texts embedded in the code and that made it hard to change them to other languages (i18n). 
This PR brings 2 new titles (they are optional) that are optionally customizable (if nothing is provided, they will remain with the current defaults).
- forceFitTitle: "Force fit columns",         // default to "Force fit columns"
- syncResizeTitle: "Synchronous resize" // default to "Synchronous resize"
Since there are defaults provided, this change will be totally transparent to most users, it will just adds possible customization to user who wants to change these text.
=> Fix #176 add customizable picker title for i18n purposes

controls/slick.columnpicker.js, controls/slick.gridmenu.js, examples/example-grid-menu.html, examples/example-plugin-headermenu.html
Added an event to the column picker that is published when the visible columns are changed.  This was important in an app I have in which there are many (over 100) possible columns to display, and a separate message needs to be sent to the server to tell it which columns are currently being shown, so that the data returned can be filtered server-side to only include the visible data.
=> Publish event when columns changed via the column picker

controls/slick.pager.js
Addresses issue #189 
The displayed page number was zero based, meaning that the pager would show something like "Showing page 0 of 1".
This is fixed by adding one. I believe this was a bug introduced in c30867d02b269674ab27f2fffa755c7339fc8ff0 (before which, one was added to the page number to be displayed).
=> Fix displayed page number being zero-based.

plugins/slick.cellselectionmodel.js
If selectActiveCell was set to false, and pasting text into a cell the
action would only work one time, and then wouldn't update again. As
selections are cleared everything seems to be working as expected.
=> BUG: Clear selection if selectActiveCell is False

plugins/slick.cellexternalcopymanager.js
If a newRowCreator is not provided as part of the options, rows that
exceed the available cells will be ignored.
=> Only add new rows if a newRowCreator is provided

controls/slick.gridmenu.js, examples/example-grid-menu.html
- Add show/hide flags for "Force Fit Columns" and "Sync Resize" checkboxes in the Grid Menu
- All add the missing events unsubscribe in the destroy method
Related to PR [#186](https://github.com/6pac/SlickGrid/pull/186)
=> Add show/hide flags for "Force Fit Columns" and "Sync Resize" checkboxes in the Grid Menu

controls/slick.columnpicker.js, examples/example4-model.html
Supersede #185 and #186, also related #195, thanks to @caroph for the original PR.
As per @6pac suggestions
- The original properties starting with `disableX` got renamed to `hideX`
- `hideForceFitButton`
- `hideSyncResizeButton`
- Also replaced `defaults.x` to `options.x` as suggested
Tested the following
- [ok] omit both hide options, both checkbox are shown
- [ok] hide 1st option (forceFit), show 2nd option (syncResize)
- [ok] hide 1st option (syncResize), show 2nd option (forceFit)
- [ok] hide 1st option (syncResize), hide 2nd option (forceFit)
=> Add show/hide flags for "Force Fit Columns" and "Sync Resize" checkboxes in the Column Picker

examples/example-plugin-headermenu.html, plugins/slick.headermenu.js
Another improvement for the Header Menu Plugin.
This plugin is nice but it has a flaw, it's always align to the right and if the last column (on the right) is too close to the edge of the browser or the viewport, we cannot see the entire menu.
So this PR fixes that problem, I added 2 new options which is `autoAlign` (defaults to false so that it doesn't break change previous behavior of always showing drop menu on the right), the other option is the `width` which the `autoAlign` need for simulating a left align of the drop menu. I also created a new function `setOptions({ })` because I need it for the demo, to enable/disable the `autoAlign` with a simple button click. 
How does it work?
Auto-align (defaults to False), will calculate whether it has enough space to show the drop menu to the …
=> [feature] Header Menu plugin autoAlign

controls/slick.gridmenu.js
We shouldn't resize the headerRow when it doesn't even exist. This fixes a visual UI problem that I ran into.
=> fix resizeHeaderRow should only work when showHeaderRow is enabled

slick.editors.js
In a text cell, when navigate by left & right arrow keys, the current behaviour is to move the cursor within the text. When the cursor is at the beginning and end of the text, pressing left / right respectively doesn't do anything. I think a better behaviour is to jump to the left/right cell instead.
See screen capture:
=> Smart handling of keydown.nav

slick.grid.js
This fixes the error reported in issue #68 with a `Slick.RowSelectionModel({selectActiveRow: true})` was not triggering properly the Editor. 
What was happening is that the Editor was getting triggered but canceled out by the row selection. The fix is to set the `setActiveCellInternal` function 4th argument to `True` (that arg is `suppressActiveCellChangedEvent`). This makes the Editor to work correctly and doesn't trigger the cell active change. Also we want to do this only when our Grid is Editable. 
@6pac 
Totally sorry about the last commit made on Master, I was supposed to be in my own bugfix branch but forgot to create the branch before pushing the commit. So I reverted the change... Again sorry about that. 
1. Double-click to Edit and `selectActiveRow` to False
-  `autoEdit: false` …
=> fix issue #68 editor with activeRow selection

controls/slick.gridmenu.css, controls/slick.gridmenu.js
- GridMenu was not working correctly with multiple grids
- GridMenu was not showing correctly in a Modal Window because it's `z-index` was too low
- Also found event leak, GridMenu should be destroyed on grid destroyed
- Tested with 2 grids in the same page
- Commands clicked on 1st grid Grid Menu should not affect 2nd grid
- Destroying 2nd grid should destroy it's GridMenu as well & it's events attached without affecting the GridMenu of 1st grid
- After 2nd grid is destroyed, we test that 1st GridMenu still work as expected
=> fix(gridMenu): GridMenu with multiple grids & event leak

slick.grid.js
Possible quick fix for issue reported in #242 
The new flag `suppressActiveCellChangeOnEdit` is disable by default but can be enabled to bypass error reported in #68
=> bugfix(editor): add a flag to suppress active cell changed on edit #242

controls/slick.columnpicker.js
- exposing the init() function helps dealing with i18n translation without losing any Slick.Event attached like onColumnsChanged
- added a global `_grid` object to make it distinct from the local `grid` object used inside the `init(grid)` function. You can refer to the Grid Menu Control for reference.
=> feat(picker): Column Picker expose init to use by translation

examples/example-grid-menu.html
@6pac 
as per your comment, here's a demo of the "autosizeColumns" in action. The biggest reason I use it instead of the "forceFitColumns" (which has to be `false` for the `autosizeColumns` to work) is that it won't affect the minimum width of a cell, meaning that it can expand but it won't shrink as much the other cells (like the `forceFitColumns` does which is more aggressive per say). 
I modified the Grid Menu example to disable `forceFitColumns: false` and instead use `grid.autosizeColumns()` when the menu closes with `onMenuClose` event. The result is shown below
I didn't put the following code in the PR, but if we add the following, it also works (let me know if you want that piece of code to be included as well in the PR).
```javascript
grid.onAutosizeColumns.subscribe(function(e, …
```
=> feat(demo): add demo for testing grid.autosizeColumns fn, ref #264

examples/example-checkbox-header-row.html, examples/example-checkbox-row-select.html, plugins/slick.checkboxselectcolumn.js
This PR was created to address a small styling issue I have seen. Our app has some grids with Column Header Titles with up to 3 rows (or even 4 rows) of text because the text is too long. The fact that the Checkbox Selector (select all) shows up in these Column Titles and top aligned is not always pretty. Since all of our grids have the Column Filters (header row) enabled, this PR provide a way to display the Checkbox Selector in that Filter Row.
- add a way to show the Checkbox Selector (select all) inside the Header Row (aka Filter row) via a new flag boolean ~`showInFilterHeaderRow` false~ `hideInFilterHeaderRow` true by defaults
- keep previous behavior of showing Checkbox Select in the Column Header Title Row, via a new flag ~`showInColumnTitleRow`, true~ `hideInColumnTitleRow`, …
=> feat(checkbox): add way to show Checkbox Selector in Filter Row

.npmignore
First commit cleans up .npmignore to sort the entries and add a missing trailing newline.
Second commit adds `tests` and `examples` to .npmignore so that they're not included in the final bundle published to npm. Saves a couple hundred KB on the final package and anyone that wants to see the tests can always go to the core repo.
=> Clean up .npmignore and exclude test/examples from final npm bundle

examples/example-plugin-headermenu.html
When grid option "multiColumnSort " set to true. 
If you hide sorted column, you need to remove it from the sort columns array too.
grid.getSortColumns => filter hidden column => grid. setSortColumns
=> Fix hidden sort column when multiColumnSort = true

slick.grid.js
- without this in place, if the user happens to be editing a field and it's field is invalid (via Validator) it will then break all Editors and force user to refresh his browser to get all Editors back. This is quite problematic and can easily be fixed by skipping any row selection if we know that we have an active editor and that fixes it. 
Tested with the Editor example by adding Row Selector and added a `console.log` to see if it would ever be hit with an else condition. The `setSelectedRanges` was triggered by the `onClick` subscribe (when a user tries to click from 1 cell to another, it will try to select the row). 
Basically the new changes is
```diff
+ if (!grid.getEditorLock().isActive()) {
selectionModel.setSelectedRanges(rowsToRanges(rows));
+ }
```
and I tested with the …
=> fix setSelectedRows should bypass when editor is active, closes #278

slick.grid.js
@6pac 
I'm so sorry, I don't know how I could have missed this (lack of coffee). I totally broke the `setSelectedRows` and that could impact lot of users. Could you merge this, which I fully tested locally, and release another version. 
This PR is to close issue #301
=> fix grid variable not exist in setSelectedRows, closes issue #301

plugins/slick.draggablegrouping.js
- this helps in knowing who caller the update action and user can do certain thing accordingly with this new info
Small improvement, and help for the first issue I had opened earlier #299. 
I want to know who called the update (is it the group sort, add group, remove group, ...) and this PR does exactly that.
=> feat(grouping): add caller/originator to updateGroupBy on Draggable Grouping

plugins/slick.rowdetailview.js
The function `calculateOutOfRangeViews()` is somehow complex and doesn't work correctly on my side, however a much simpler version always work for me and I'm providing it as an alternative calculation method that can be enabled by a new flag `useSimpleViewportCalc` (which is disabled by default to keep previous behavior). Providing an alternative has the benefit of not breaking the old code while making my side work as intended without breaking anyone else code.
=> WIP - row detail view - provide alternative calculation

controls/slick.gridmenu.js
- without the fix, if 2 grids exists in the same page and 1 has header row showing, and the 2nd grid is not, 1 grid will affect the other. The fix is to use the grid UID to avoid such problems.
=> fix(gridmenu): should be using grid UID for menu independence

slick.grid.js
A lot of time we want to know when the grid got rendered and there's no official way of knowing it (until this PR). This event also brings ability to know the top/bottom visible rows whenever they change. Code was copied from another fork.
=> add new event: onRenderedEvent

plugins/slick.rowdetailview.js
- Use the new `onRendered` event that was added recently and delete the previous `setTimeout` code that was not always working
- also found 2 subscribed events were not destroyed because we were not using the correct Slick Event Handler
=> row detail plugin, use new onRendered event

slick.grid.js
- dataset often comes from backend and is delayed, data length doesn't always exist
Found this small issue while using async dataset.
=> fix empty dataset throws an error on start

controls/slick.gridmenu.css, controls/slick.gridmenu.js, examples/example-grid-menu.html, examples/example-plugin-headermenu.html, plugins/slick.headermenu.css, plugins/slick.headermenu.js
This brings the possibility to add a `divider` between Header Menu & Grid Menu items, see print screen below (where the red arrow points to). This helps with very long list of menu commands.
=> feat(divider): add divider option to Grid Menu & Column Header Menu

examples/example2-formatters.html, slick.grid.js
This bring the possibility, which I need in my project, to add a tooltip (title attribute) to a Formatter when using it as an extended object (as shown in Example 2). Note that the property `toolTip` was already available to column header, so I used the same property name and provided it as a new option for cell formatters as well. :)
See the animated gif for the demo of the feature
=> feat(formatter): add toolTip to Formatter with extended object

slick.grid.js
When the grid initialises it only handles the mouse wheel if either frozen columns or frozen rows have been set.  This results in a bug, whereby if frozen columns or rows are set after the grid has initialised, then placing the mouse over the frozen area and using the scroll wheel results in no scrolling.  In this circumstance it will only scroll when the mouse is placed in the non frozen area.  
Always handling the mousewheel, when the jQuery mouseWheel plugin is set, fixes this issue.
=> Fix grid scrolling using mouse wheel, when frozen column/row is set after the grid is initialised

examples/example-frozen-columns-and-rows.html, examples/example-frozen-columns-tabs.html, examples/example-frozen-columns.html, examples/example-frozen-rows.html
- all frozen examples have the "set" button in the wrong location, it's a simply styling visual fix
I will merge this PR right away since it's simply cosmetic styling fixes, it only put the button "Set" at a proper location (on the right side of each inputs). See below for the differences
Before
After
=> fix(examples): simple button alignement fixes

plugins/slick.cellrangeselector.js
- the issue was that if user open the example "example-frozen-columns-and-rows-spreadsheet.html" and he scrolls completely at the bottom of the frozen grid (bottom right) and try to select a cell range, it was not selecting properly
reference issue #329
This is a Work in Progress (DO NOT MERGE YET)
We need to do some more test before merging
=> fix(selector): cell range selector was not working when at bottom

slick.grid.js
- [onSelectedRowsChanged](https://github.com/6pac/SlickGrid/blob/master/slick.grid.js#L2259) should ONLY trigger when new selected rows are different compare to previously selected rows
- the issue comes from "slick.checkboxselectcolumn.js" that has a subscribe to "onSelectedRowsChanged" and when copying text selection, this was triggering a row selection (which is incorrect when row was already selected and doesn't change) and this in turn was calling an "invalidateRow" which finally removes focus of the cell
This fixes issue #334 (and possibly #150), in brief user cannot copy text selection when row is the selected row (even when it's the same selected row). Also note that I have `enableTextSelectionOnCells` enable but that was not helping with my issue. This was also mentioned in a …
=> fix(selection): copy text selection now working, closes #334

plugins/slick.cellrangeselector.js
- the error is not showing up if user tried scrolling at first, the small issue is related to the fact that 2 variables scrollTop, scrollLeft were not initialized
closes #336
=> fix(selector): cell selector throws error in console when no scroll

slick.grid.js
Issue reference #332
This old patch was to fix a Mac only (Chrome on Mac) problem, however this patch is no longer necessary since the Chrome problem got fixed 2 years ago ("Work around http://crbug.com/312427." - Inertial scrolling bug in WebKit/Blink in Mac OS X breaks virtual list implementations). This in terms fixes issue #332
=> fix(overflow-scrolling): remove old patch now unnecessary, closes #332

examples/example-checkbox-header-row.html, plugins/slick.checkboxselectcolumn.js
- provide a way to define if a row can be selectable or not through a method that can be override
- fixes #343
```js
var checkboxSelector = new Slick.CheckboxSelectColumn({ ... });
// make only Even Rows selectable by overriding canRowBeSelected callback
checkboxSelector.canRowBeSelected(function(row, columnDef, dataContext, grid) {
return dataContext.id % 2;
});
```
What do people prefer to use as the method to override? 
1. `selectableOverride` 
2. `canRowBeSelected`
We are going with `canRowBeSelected` as this is more readable and obvious.
=> feat(selectable): add override method to know which row is selectable

plugins/slick.cellselectionmodel.js
- summary of the issue explained: The ranges variable returned from getSelectedRanges() is a member variable, which is being passed to the setSelectedRanges function on line 172. In the setSelectedRanges, the same member variable is being compared to itself, resulting rangeHasChanged false. So, I can't change selected range using keyboard with shift Key.
Thanks for the help of @SatanEnglish, I tested the small change and confirm what we see below with the animated gif. Doing a deep copy with `slice()` does fix the issue. 
Using Shift + Arrow keys, Before the fix
Using Shift + Arrow keys, **After** the fix
=> fix(cellSelection): deep copy so we can use of shift+arrow, closes #341

slick.grid.js
This fixes autoheight if there are multple header rows (e.g. column grouping).
With autoHeight set to true, and a plugin that creates column groups by adding an additional <div> to the `<div class="slick-header ui-state-default slick-header-left">` element, the calculated height was ignoring this additional space, resulting in the final row being hidden.
By using `$headerScroller`  to calculate the header height, we take the height of the containing element, which incorporates any additional column grouping headers and the height is set correctly.
=> Use $headerScroller to calculate height instead of $headers

examples/example-checkbox-header-row.html, plugins/slick.checkboxselectcolumn.js
- to stick with a convention having the word override in the method name to easily identify what the method does
This is just a rename for convention purposes, it renames the override method previously added in PR #343 to the new name `selectableOverride`, to easily identify what the method does
Example with the new name
```js
var checkboxSelector = new Slick.CheckboxSelectColumn({ ... });
// make every 2nd selectable by providing custom logic
checkboxSelector.selectableOverride(function(row, columnDef, dataContext, grid) {
return dataContext.id % 2;
});
```
=> refactor(selection): rename override to selectableOverride

examples/example16-row-detail.html, plugins/slick.rowdetailview.css, plugins/slick.rowdetailview.js
Similar to what we did with PR #346 on Row Selection with an override method, let's add the same feature to the Row Detail Expandable. The override method is named `expandableOverride` and follows the exact same concept as the PR #346 
Example
```js
// make only every 2nd row an expandable row,
// by using the override function to provide custom logic of which row is expandale
detailView.expandableOverride(function(row, dataContext, grid) {
return (dataContext.id % 2 === 1);
});
```
=> feat(rowDetail): add override method to know which row is expandable

controls/slick.gridmenu.js
- we do this because the GridMenu is pushed on the body so adding this adds a way to associuate the grid menu with the correct grid
=> feat(gridMenu): add grid UID to the GridMenu control

examples/example16-row-detail.html, plugins/slick.rowdetailview.js
- this was throwing an error when user doesn't have a global "grid" instance, this was not showing up in the example 16 because it has a "grid" global variable
- also add new way of passing the override method, user can now also pass it directly in the plugin options. So we can now override via the options or via the plugin instance.
=> fix(rowDetail): override formatter, don't use global grid instance

examples/example11-autoheight.html, slick.grid.js
fixes #356 
- The grid shown below has 100 items (0 to 99) and now shows the scrollbar correctly when needed. 
- Also tested with/without setting width on each columns, so it really only shows scrollbar when needed.
- Tested with all Frozen grids as well (there is also an autoHeight frozen grid)
- Lastly tested as well in my repos, seems all fine.
=> fix(autoHeight): horizontal scroll not showing when needed, fixes #356

slick.grid.js
- supersede PR #209 (that older PR was done prior to the frozen feature)
- this fix avoid some grid using autoheight to go circular reference (2 references calling each other).
The infinite loop comes from 2 references calling each other until the browser crashes with maximum calls. The reference is `updateRowCount()` calls `resizeCanvas()` which calls `updateRowCount()`, and so on... This only happen, and is only possible, with the flag `autoHeight` enabled.
=> fix(autoheight): updateRowCount shouldn't set virtual height, fixes #364

slick.grid.js
There was an small issue with getPluginByName function which eventually never returns plugin. It starts with index equals to the length of plugins array and throw undefined error on line 620 due to index out of range
=> Fixed an issue with getPluginByName function

plugins/slick.rowdetailview.js
- this is a small fix that was already discussed in this [post](https://github.com/6pac/SlickGrid/pull/351#issuecomment-469947531) but I forgot to apply it earlier.
=> fix(plugin): Row Detail always show a scroll even when has enough space

slick.grid.js
Fixes issue (#371) with large numbers by removing the bitwise operation used on row index. I did not change bitwise operations done against column indices.
=> fix #371 for number larger than 2.14 billion

controls/slick.columnpicker.js, examples/example4-model.html
Similar to PR #376 but for the Column Picker
Option to exclude certain column header(s) from the Column Picker. 
For example, print screen below shows that the "#" column header is excluded from the Column Picker.
The code is the following: 
```js
var columns = [
{ id: 'id', field: 'id', name: 'Id', width: 40, excludeFromColumnPicker: true },
// ...
];
```
=> feat(columnPicker): add columnDef option to exclude a column from picker

controls/slick.gridmenu.js, examples/example-grid-menu.html
Option to exclude certain column header(s) from the Grid Menu. 
For example, print screen below shows that the "Id" column header is excluded from the Grid Menu.
Another PR for the same feature on the Column Picker will follow.
The code is the following: 
```js
var columns = [
{ id: 'id', field: 'id', name: 'Id', width: 40, excludeFromGridMenu: true },
// ...
];
```
@6pac 
Also note, that I slipped a [commit](https://github.com/6pac/SlickGrid/commit/bfe6512b3dc6c5ea2585661bd134dff56ec335b0) about Row Detail without a PR by mistake (forgot to create a new branch on my local before I push). Sorry about that, the info is all in the PR.
=> feat(gridMenu): add columnDef option to exclude a column from grid menu

slick.grid.js
When calling `updateRowPositions()` on a large table it was not appropriately getting the `rowNode` which caused a `could not get style of undefined` error. Getting the first element of the rowNode array fixes the issue.
Note: I refactored the row parseInt logic into a function to prevent the duplication of code.
Thanks!
=> fix style of undefined rowNode

examples/example8-alternative-display.html, slick.grid.js
I have a use case where I need to display one record per a cell rather than the usual per a row. This means the column title is superfulous and I want to remove it (also saves some UI space).
Another use case could be where the cell content is almost self-expanitory like in [example8](http://6pac.github.io/SlickGrid/examples/example8-alternative-display.html).
I haven't tested this much but the option defaults to off so it shouldn't affect any existing code.
=> add option to hide column names

slick.grid.js
- remove any 0 padding of Date argument (e.g. 08 should be 8)
- moment.js doesn't accept array as argument
As per this [comment](https://github.com/6pac/SlickGrid/issues/392#issuecomment-511663019) found in issue #392 
The parsing error thrown in Aurelia-Slickgrid while doing a build is the following
```bash
ERROR in ./node_modules/slickgrid/slick.grid.js
Module parse failed: D:\OwnSyncDev\GitHub\aurelia-slickgrid\node_modules\slickgrid\slick.grid.js Invalid number (2212:52)
You may need an appropriate loader to handle this file type.
|         }
|         if (colDataTypeOf === 'date') {
|           autoSize.colValueArray = [ new Date(2009, 08, 30, 12, 20, 20) ]; // Sep 30th 2009, 12:20:20 AM
|         }
|         if (colDataTypeOf === 'moment') {
```
EDIT
It seems that Moment.js might …
=> fix(build): fixes a parsing issue found while builing Aurelia-Slickgrid

controls/slick.columnpicker.css, controls/slick.columnpicker.js, controls/slick.gridmenu.css, controls/slick.gridmenu.js
- found this issue by looking into adding Cypress E2E tests, ref PR #399
- because there is a grid `setColumns`, we cannot just remove the excluded columns, if we do it causes some issues when clicking checkbox to show/hide columns later. It removes the excluded column completely from the grid as soon as we click on the checkbox of any item, that is because we call the `setColumns` without the excluded item.
- what is better is to simply keep excluded item in the list but simply hide the checkbox from the picker list.
From the animated gif below, you can see the 2 first columns ("#" and "A") hides when clicking only item "A"
=> fix(picker): column exclude from ColumnPicker, GridMenu caussing issue

examples/example8-alternative-display.html, slick.grid.js
As discussed in this [post](https://github.com/6pac/SlickGrid/issues/392#issuecomment-512641456), 
remove all `showColumnLabels` and replace by `showColumnHeader`, also tested the `example8-alternative-display.html`. My repos are also all working as expected, so that does seem like a typo and using only `showColumnHeader` is what we needed from the start.
@6pac 
Can we remove all the `LogColWidths()` calls or do you still need them? I don't mind leaving the method there, but I'd like to at least comment out the method calls.
=> fix(header): remove all showColumnLabels and replace by showColumnHeader

.gitignore, .npmignore, .vscode/tasks.json, cypress.json, cypress/integration/exampleGridMenu.spec.js, cypress/plugins/index.js, cypress/support/commands.js, cypress/support/index.js, examples/example-grid-menu.html, package.json
I think it's time to start looking at adding E2E tests (UI testing). We used to have Selenium back in the days, but that was hard to install and run. The JavaScript world have come a long way and new tools, the best tool that I've found so far and is super easy to install (it's all in the PR) is [Cypress.io](https://www.cypress.io), it's quite easy to program tests and it works universally. It doesn't need any framework or anything except running an npm command to install it, just run `npm install` (or `yarn`) and then run `npm run cypress:open` or even better if you have VScode, just run the task "Cypress Open GUI" that I added. Here's a quick [intro video](https://www.youtube.com/watch?v=VvLocgtCQnY) of Cypress
There's a ton of things we can do with Cypress, drag & drop, click buttons, …
=> feat(e2e): add Cypress to the project for E2E testing

slick.grid.js
When using `SlickGrid` in Angular 8 via `Angular-Slickgrid` a variable undefined error is thrown for `columnNamesH`. Adding the `var` declaration fixes this issue. Looks like the `var` declaration was added to `preHeaderH` in a previous PR.
=> Variable undefined error

slick.groupitemmetadataprovider.js
Add slick-group-level-n class to group header and total/footer rows. This will allow people to add style to various levels of the group rows, enabling users to distinguish between regular rows and group rows and much more.
In this screenshot, you can easily target the level 0 and 1 group totals:
=> Add slick-group-level-n class

slick.grid.js
The colDef.cellAttrs option allows addition of custom attributes to cells. For example, you could add the "col-id" attribute shown here:
<div class="slick-cell l0 r0" col-id="COUNTRY.COUNTRY_DESCR">Algeria</div>
by adding this to the colDef:
cellAttrs: {
'col-id': 'COUNTRY.COUNTRY_DESCR'
}
=> Ability to add custom attributes to cells

examples/example-0070-plugin-state.html, plugins/slick.state.js
Grid State plugin, uses Local Storage to keep the state of the grid and reloads the state when refreshing the grid. 
This is a simple copy/paste of the the [GerHobbelt - SlickGrid](https://github.com/GerHobbelt/SlickGrid/blob/k0stya-rowspan/plugins/slick.state.js) fork
See animated gif for a demo, the demo is to resize a few columns, change position and sort them, then refresh and everything comes back since we use Local Storage to save/restore the Grid State
=> feat(gridState): add a new Grid State plugin with example

lib/jquery.event.drop-2.3.0.js
Sometimes when dragging & dropping rows, elem is document and offset can't be calculated on document
=> Prevent offset+getClientRects error when elem is document

slick.dataview.js
In getRowDiffs(), the "to" variable is set to newRows.length. As an example, if newRows.length is 1 and rows.length is 2, the for loop only iterates from 0 to 1, and thus not detecting any difference so long as the first item in both newRows and rows remain the same.
I also had to add a check for !item. In the example above, newRows[1] would not exist.
Here's an example of the bug in action. Notice when I type "af", it shows two rows for Afghanistan and Africa, but when I add "afg" it does not get rid of Africa:
=> Bug in getRowDiffs() causing incorrect filter

.npmignore, cypress/integration/exampleGridMenu.spec.js, package.json
This enhances previous basic test of the Grid Menu Example into a full test suite. Currently the last test will fail, because of issue #424, once that issue is fixed then the test should pass. See below for animated gif of the full test. To test it on your computer, you need NodeJS, then run the following 2 commands: `npm install` and then `npm run cypress:open` and finally click on the "Run all specs" button once the Cypress UI opens.
Also I removed the Cypress folder from the NPM package, it shouldn't be there on the final bits, it should only be in Git
@6pac 
If you have a chance, could try to install Cypress and see if you get the same result. This should help for future commits in the repo.
=> feat(cypress): add Cypress E2E Grid Menu full test suite

examples/example-frozen-columns-and-column-group.html, slick.grid.js
Created the preheader panel, scroller and spacer elements for the right side panel, and bound scrollLeft to the right panel when frozen columns are set.
Exposed the right preheader panel via public getter for constructing the column group headers.
Added example of usage.
Fixes #340
=> Enable Frozen Columns with Column Grouping

slick.groupitemmetadataprovider.js
Option called includeHeaderTotals to show totals in group header row. When combined with "aggregateCollapsed: false", it makes for a very clean look when collapsed.
=> Group Header Totals

slick.grid.js
toggleCellClass is now at the main function level, otherwise uglifyjs-webpack-plugin gives the following error:
_In strict mode code, functions can only be declared at top level or immediately within another function._
=> Moved code around in flashCell

slick.dataview.js
I'm receiving the following error message on a WebKit browser for a very popular analytics product called Tableau:
> TypeError: Attempting to change writable attribute of unconfigurable property
This fix simply catches an error, if there is one, and uses the default method of setting `fn.name`
Here's a screenshot of the error being thrown:
=> Fix Object.defineProperty error

slick.grid.js
If there is no footer row on the grid, and you call `grid.getFooterRowColumn(colId)`, then you'll get an error. I realize that you shouldn't be calling this function if you don't have a footer, but I did accidentally and this simple fix will help in case others do the same.
=> Fix error for $footerRowTarget undefined

slick.grid.js
If a column has all empty values, `maxIndex` will be undefined in [this](https://github.com/6pac/SlickGrid/blob/master/slick.grid.js#L2359-L2369) code block, so this error will be thrown:
```
Uncaught TypeError: Cannot read property 'DIM_DOCUMENT.SUPPLIER' of undefined
at getColContentSize (slick.grid.js:2367)
at getColAutosizeWidth (slick.grid.js:2276)
at SlickGrid.autosizeColumns (slick.grid.js:2132)
at child.refresh (grid.js:570)
at grid.js:579
```
Also, I removed `maxIndex` from [this](https://github.com/6pac/SlickGrid/blob/master/slick.grid.js#L2345-L2357) code block because it is unused.
=> Fix 'Cannot read property of undefined' error

controls/slick.gridmenu.js
- fixes the previous commit to fix the same issue, we should allow frozenColumns to be 0 or more and we should check that the `frozenColumn` property exist
- fixes #436
=> fix(gridMenu): Menu should work with Frozen Col 0, fixes #436

examples/example16-row-detail.html, plugins/slick.rowdetailview.js, slick.dataview.js
- added a new `getIdPropertyName()` method to pull current "id" property name used in the DataView, this is required for external plugin to know what it is without specifically asking the user to pass it to every plugin
- added a new Slick  Event `onSetItemsCalled` in DataView to know when the DataView was last called, only then we know the "id" property name
- fixes #420
=> fix(rowDetail): work with DataView custom "id" property name, fixes #420

controls/slick.columnpicker.js, controls/slick.gridmenu.js, examples/example-grid-menu.html
- prior to this fix, the "visibleColumns" was not taking into consideration columns that could be hidden from the column picker in addition to the picker in the grid menu
- prior to this fix, the "fadeSpeed" was pulled from the grid options which was the wrong place to get the option
@6pac 
You can merge whenever you want and there's no need for a new release, that can certainly wait
=> fix(picker): incorrect output for visibleColumns & fadeSpeed option

lib/jquery.event.drag-2.3.0.js
- closes #239 
- tweak `jquery.event.drag` so that it only drag DOM elements that are own by a SlickGrid. The fix is to only allow a drag if the target element css class name starts with "slick" so that we know that we are inside a grid, else disregard the drag. That fixes all external lib issues.
The fix was tested with a grid and Froala Editor (an older version of the lib, `2.3.5` that was reported as having issues). Before the fix, the Froala Editor is not usable, though after the fix it's all good and usable. I also tested a few SlickGrid Examples to make sure that nothing was broken (column resize, column drag, draggable grouping, cell selection with external cell copy) and everything is also fine with SlickGrid.
Demo 
without (trying to click the editor doesn't work), then with the …
=> fix(drag): make sure drag event are only for slickgrid, fixes #239

controls/slick.gridmenu.js, cypress/integration/example-grid-menu.spec.js, cypress/integration/example-plugin-contextmenu.spec.js, cypress/integration/example-plugin-headermenu.spec.js, examples/example-grid-menu.html, examples/example-plugin-contextmenu.html, examples/example-plugin-headermenu.html, plugins/slick.cellmenu.js, plugins/slick.contextmenu.js, plugins/slick.headermenu.js
=> feat(menus): add "onAfterMenuShow" event to all possible menu plugins

cypress/integration/example-checkbox-header-row.spec.js, examples/example-checkbox-header-row.html, package.json, slick.grid.js
- Add the previously selected rows into the `onSelectedRowsChanged` to know what was selected before the new selection.
=> feat(selection): add previousSelectedRows into "onSelectedRowsChanged"

slick.dataview.js
Updated the dataview.js to add Slick.Event for expand and collapse actions within data view groupings. fixes #462
=> Add expand/collapse grouping events

plugins/slick.cellmenu.js
- this fixes an issue found with Row Selection which also uses the onClick event and because the cellMenu was preventing bubbling, it was breaking multiple row selection. That is why we should prevent bubbling only on column that do have a cell menu, else just keep going with regular bubbling
=> fix(cellMenu): stop event bubbling only on valid cell menu column

slick.grid.js
- fixes #275
As discussed in the issue, this PR does the following
currently using append to `$viewport`
```js
var $outerdiv = $('<div class="' + $viewport.className + '" ...).appendTo($viewport);
// measure... {width: 8, height: 8} 
```
the code change to fix the issue is to append to `body` 
```js
var $outerdiv = $('<div class="' + $viewport.className + '" ...).appendTo('body');
// measure... {width: 17, height: 17} <-- CORRECT
```
@6pac 
I tried every single Examples and I couldn't find any issues or misbehavior with this change. You can do some more tests on your side if you want, feel free to merge at any time. 
Thanks
=> fix(resize): measure scrollbar from body instead of viewport, fixes #275

slick.grid.js
With Chrome at certain zoom levels, the `clientHeight` of `$viewportScrollContainerY[0]` is reported as being 1 pixel larger than the `scrollHeight`.
I think this may actually be a Chrome/Chromium bug as I don't think this should ever occur.
When this occurs and the `autoHeight` is set to true in the SlickGrid options, `th` is used in calculations even though it is `undefined`. This causes the grid to fail to render.
This pull request just protects against a negative value in `scrollTop` or `scrollLeft`.
Without changes in this PR:
With changes:
=> Protect against negative scrollTop/scrollLeft in _handleScroll

plugins/slick.checkboxselectcolumn.js
- when using "hideSelectAllCheckbox" flag, the tooltip "Select/DeSelect All" should not be showing anymore
=> fix(plugin): remove unnecessary tooltip when checbox hidden

README.md, cypress/integration/example-row-detail-selection-and-move.spec.js, examples/example-row-detail-selection-and-move.html, package-lock.json, plugins/slick.rowdetailview.js, plugins/slick.rowmovemanager.js
DO NOT MERGE YET - I still want to add Cypress E2E tests before merging
- closes #347
- this PR allows to use 3 plugins (RowDetail, RowMoveManager & CheckboxSelector) all at the same time. Our new project requires at least 2 of the 3 to be used together. 
- in order to achieve that, I added 2 new options to the Row Move Manager Plugin, the new options are (singleRowMove & disableRowSelection) and their default are set to false so it doesn't break anyone's code
- the main changes are done in the RowMoveManager plugin, while a couple of changes were also made in the RowDetail Plugin so that all 3 plugins all work nicely together. A new Example was added as well to demo all 3 plugins in 1 grid, Cypress E2E were also added
See animated gif below for a demo
demo with `usabilityOverride` …
=> feat(plugins): add ways to use all 3 plugins together, closes #347

plugins/slick.rowmovemanager.js
- without the `text: ""`, it was showing `undefined` beside the icon in some occasion when the grid gets re-render.
- also note that the built-in formatter was added fairly recently in this previous PR #474 
Reference, you can see the 3 dots and `undefined` in html code
=> fix(plugin): Row Move Formatter should have empty text value

plugins/slick.rowdetailview.js
- this issue is only noticeable when using "useRowClick: false" and a different dataViewIdProperty
- ref Angular-Slickgrid [issue](https://github.com/ghiscoding/Angular-Slickgrid/issues/440)
=> fix(rowDetail): use column id instead of item id

slick.dataview.js
Sort may rely on totals, so we need to call addTotals(groups) before groups.sort()
=> Total groups before sort

README.md, cypress/integration/example-row-detail-selection-and-move.spec.js, package-lock.json, package.json, plugins/slick.rowmovemanager.js
- we should not allow a row to be moved where it's not possible (where the "usabilityOverride" returns false)
in the Example shown below, we should only allow to move a row on every 2nd row (before or after the row move icon is displayed). When I introduced the "usabilityOverride" in PR #474 I forgot to check that condition, this PR fixes it.
=> fix(plugin): check usabilityOverride before accepting new position

slick.grid.js
- this PR allows to disable the built-in slide animation (which uses jQueryUI), I have a particular use case where I toggle the filter bar after the grid creation and I don't want to see the animation at all, it has to happen instantly without the user noticing the filter header row was ever open.
- added a boolean flag as 2nd argument to each functions, the default is still the animation, so it won't change default behavior
- note the gif start with animation, then later reload the page and disable all animation with extra false argument
=> feat(animation): add option to disable animation on all setVisibility fn

slick.grid.js
=> fix(core): `resizeCanvas` should include preheader height, fixes #493

plugins/slick.cellrangedecorator.js
- this PR is to make sure that from/to and offset exist before trying to get their values, this might fix issue brought up in #488 with drag on mobile.
- it might not fix the issue in #488, but it should get rid of the errors thrown in the console. 
- ref #488
=> fix(plugin): make sure from/to exist before getting values, ref #488

controls/slick.columnpicker.js, controls/slick.gridmenu.js
- there was an issue happening after toggling the "Force Fit Columns" flag when having hidden columns, it was not respecting the list of columns and hidden columns were coming back as visible even though they were hidden prior to the flag change. In other words, calling "Force Fit" shouldn't change any column visibilities.
- this issue was first reported in this [issue](https://github.com/ghiscoding/Angular-Slickgrid/issues/461) on the Angular-Slickgrid lib.
The issue was mentioned as the following
> I mean when i hide some column 
and then i click 'Force Fit Columns' I get all columns but I expected to get columns without 'Effort Driven'
=> fix(picker): ColumnPicker/GridMenu exclude hidden cols when forceFitCols

controls/slick.gridmenu.js, examples/example-frozen-columns-and-column-group.html, examples/example-grid-menu.html
- The `headerColumnValueExtractor` is especially useful when having Header Title Column Grouping if we want to include the title as part of the column picker list within the Grid Menu
- add a new `contentMinWidth` grid menu option
- add a new `useClickToRepositionMenu` grid menu option, which use the click offset or the icon offset (when false) to reposition the grid menu
- lastly, I also fixed issue #490 by making the grid menu also work with keyboard event (ENTER)
When I created the Grid Menu control, I forgot to include the `headerColumnValueExtractor` function that the Column Picker already has, this is really helpful when having a grid with Column Header Title Grouping as can be seen below
@6pac in case you're wondering, @ghiscoding-SE is my work GitHub account, I work for Schneider …
=> fix(gridMenu): add missing "headerColumnValueExtractor" to Grid Menu & fix #490

controls/slick.columnpicker.js, controls/slick.gridmenu.js, cypress/integration/example-multi-grid-basic.spec.js, examples/example-multi-grid-basic.html
- ColumnPicker & GridMenu Picker should work independently
- There was an issue with the independence of each picker because the checkbox labels were sharing the exact same label text (because both grids had exact same column headers) and that caused side effect that clicking on bottom grid checkbox picker would actually change the 1st grid instead of 2nd grid and vice versa... that was caused by checkbox label not being unique
- add uniqueness by adding the grid UID to each checkbox labels
- this bug impacted both the ColumnPicker & the GridMenu and was only happening when having tow or more grids in the same page with same column headers
This bug was hard to find, I thought I had a Singleton issue but it turns out to simply be that each Checkbox Label **must** be unique in their names. …
=> fix(pickers): ColumnPicker/GridMenu with 2 independent grids

slick.grid.js
- the PR #497 was wrong and should be rolled back since the pre-header height is already calculated by getViewportHeight() which is called in the resizeCanvas() method.
- rollback #497 - ref #493
=> fix(core): rollback PR #497 which is now causing resize issue

controls/slick.gridmenu.js
When determining the max-height of the context menu, we should be basing the Y coord on the size of the viewport and the position from the top of the viewport.  Using pageY is measuring the mouse position from the top of the page, not the viewport.  This request changes the pageY to clientY in order to correctly calculate the position of the mouse from the top of the viewport and ensure the menu doesn't extend below the viewport, and is also big enough to use.  For very large pages, when the grid is towards the bottom, the size of the menu was being set to an unusably small value.
=> Fix menu max-height.

controls/slick.gridmenu.js, package-lock.json, package.json
- also update few npm packages
- this PR is in reference with a discussion started in PR #502
=> fix(gridMenu): add "height" and "marginBottom" options

plugins/slick.autotooltips.js
`handleMouseEnter` now checks for `$node.attur("title")` first. if `title` already exists, it doesn't update/create `title` value.
=> `title` only added if no `title` is already defined

plugins/slick.rowmovemanager.js
- while browsing for some examples (Row Move Example), I caught this console error. This fixes it
=> fix(plugin): check options exist before getting prop

controls/slick.gridmenu.js, cypress/integration/example-frozen-columns-and-column-group.spec.js, examples/example-frozen-columns-and-column-group.html, package-lock.json, package.json, slick.grid.js
- add a new SlickGrid event `onSetOptions` to know when users dynamically changes the grid from regular to frozen (or vice versa)
- the issue was that when changing a grid dynamically from regular to a frozen grid, the Grid Menu is positioned at the wrong location (shows up on left container instead of right container), the reason is because a regular grid uses the Left Grid Pane, while a frozen grid uses both left/right Grid Pane and its menu should be on the right Grid Pane (instead of left for a regular grid).
- now 100 tests in total on 9 different examples, sweet :)
you can see the grid menu showing up on the left container, on its top right, but it really **shouldn't be there**
---- 
grid menu is only on top right corner of the grid, where it should always be
=> fix(gridMenu): Grid Menu wrong location changing from regular to frozen

slick.dataview.js
- it seems that previous PR #487 brought a new regression bug, the fix is to simply pass the level to the addTotals function
=> fix(grouping): collapse all then expand sub-group, fixes #512

slick.grid.js
When frozen columns is enabled the height of the header row is missing in the height calculations.
With this change the values are also calculated in this specific case so they are available later.
This fixes #521 for me.
=> calculate hearderRowH also when having frozen columms

examples/example15-auto-resize.html, plugins/slick.resizer.js
- optional but when provided it will be resized with same size as the grid (typically a container holding the grid and extra custom footer/pagination)
TODOs
=> feat(resizer): add optional grid container to resize

controls/slick.gridmenu.css, controls/slick.gridmenu.js, examples/example-plugin-headermenu.html, plugins/slick.cellmenu.css, plugins/slick.cellmenu.js, plugins/slick.contextmenu.css, plugins/slick.contextmenu.js, plugins/slick.headerbuttons.js, plugins/slick.headermenu.css, plugins/slick.headermenu.js
- in some cases we might want to use "disabled" but in other cases we might want to use "hidden" to still have the command but just keep it invisible, this PR adds this new "hidden" property to all possible controls/plugins with menu items/commands (HeaderMenu, GridMenu, CellMenu, ContextMenu).
=> feat(plugins): add "hidden" property to all plugins with menu items

slick.grid.js
- this is to avoid having the grid reset the columns when for example we just want to change simple flags that don't have any impact on the grid or its rendering
=> feat(core): add a supressColumnSet on setOptions method

plugins/slick.rowmovemanager.js
- in some cases the formatter was showing "..." because of the text being shown as undefined
=> fix(plugins): Row Move icon formatter should have text property

slick.grid.js
- we should never show a vertical scroll on the left container when having a frozen grid, even when flag `alwaysShowVerticalScroll` is set to True (in that case, the flag should display a scroll ONLY for the right container)
- for reference, the flag `alwaysShowVerticalScroll` is only used for 1 reason, to show a vertical scroll so that the Grid Menu icon doesn't go over a header column title (see print screen 2).
**without the fix**
**with the Fix**
=> fix(core): we should never show vertical scroll on left frozen container

slick.grid.js
Our company use the slickgrid and we had an issue with the vertical scrollbar not going all the way down in some scenarios. There is a gap at the bottom and there is no way to drag the scrollbar all the way down. The horizontal scrollbar is visible and the fault is that the code does not acknowledge this. There is a line in the code that determines if the horizontal scrollbar is visible but this misses with one pixel. The changed formula uses greater than or equal instead of only greater than. I saw that this solution was proposed in a PR long time ago to mleibman:
https://github.com/mleibman/SlickGrid/pull/1030/files
=> Fix issue with vertical scrollbar not going all the way down

slick.dataview.js
- also renamed `getAllSelectedRows` to `getAllSelectedIds`
- this PR is to address this [comment](https://github.com/6pac/SlickGrid/pull/542#issuecomment-709411278)
Let's wait feedback by @arashdalir before merging
=> feat(dataView): add getAllSelectedItems function

slick.grid.js
- this is to avoid having events leaking in memory from possible detached elements
=> fix: we should remove all event listeners when calling destroy

slick.grid.js
- when using TypeScript, we must always import the mousewheel jquery lib even if we don't need it because TypeScript does not yet support dynamic import. So providing a grid option to only use the mousewheel handler when we really want it is the only bulletproof way to only use that handler only when we really need it (typically when using a frozen grid)
- ref Angular-Slickgrid [issue](https://github.com/ghiscoding/Angular-Slickgrid/issues/618)
=> feat: add enableMouseWheelScrollHandler option to allow dynamic load

slick.grid.js
this goes with PR #555, just forgot to remove mousewheel scroll handler when the option is disabled and is used by `setOptions`
=> fix: remove mousewheel scroll handler when option is disable

controls/slick.columnpicker.js, controls/slick.gridmenu.js
- in some cases it's useful to know which column from the picker triggered the hide/show
- for my use case, I need to know when a column is shown/hidden so that I can readjust the `frozenColumn` index if need be (that is if the column is on the left pinned container, I need to do +/- 1 on the index because SlickGrid doesn't automatically readjust it)
=> feat: add columnId to onColumnsChanged event

slick.dataview.js
- add item count to `onRowCountChanged`
- add item count to `onRowsChanged`
- add item count to `onRowsOrCountChanged`
- add item count to `onSetItemsCalled`
- also renamed `getItemsCount` to singular `getItemCount` so that it's aligned with the other counter. 
- note: this was a new function to get merged just 2 days ago, so it's ok to rename it now
- `onSetItemsCalled` event should be called before the refresh method since that can itself trigger `onRowCountChanged` but it has to be after the `onSetItemsCalled` event instead of before
=> feat: add item count to data change handlers

cypress/integration/example-optimizing-updates.spec.js, examples/example-optimizing-updates.html, examples/index.html, slick.compositeeditor.js, slick.core.js, slick.dataview.js, slick.editors.js, slick.formatters.js, slick.grid.js, slick.groupitemmetadataprovider.js, slick.remotemodel-yahoo.js, slick.remotemodel.js, tests/dataview/dataview.js
Resolves #571 
This PR addresses the proposed changes of #571 to have more efficient bulk update capabilities in the Data View. 
**PR Checklist** 
**Proposed Changes**
The first change is to add plural versions of the main modification methods: addItems, updateItems, deleteItems
These operations use more optimized array updates and ensure the related index lookup updates + refresh are only triggered once. 
The second change is to allow devs to indicate that bigger bulk updates are performed on the DataView. Internally this bulk update flag is then used at certain places to delay or optimize certain operations. 
For now it is used to delay the delete operations to the endUpdate call which allows a 1 time reorganization of the internal items array and the index lookup table. 
Alternative …
=> Adds optimized bulk operations to DataView

plugins/slick.draggablegrouping.js
Now, if the dropped column header contains an element with class 'slick-column-name', only the text content of that element is used to populate the dropped grouping represenation. This prevents additional column header content from being displayed (like the order number in case of sorting by multiple columns).
=> only use Colum Name for dropped Group Name

slick.grid.js
- this will help in calculation our own column widths and calling `reRenderColumns` to resize columns accordingly
=> feat: expose `reRenderColumns` as public method

controls/slick.gridmenu.js, examples/example-grid-menu.html, examples/example-plugin-contextmenu.html, examples/example-plugin-headermenu.html, plugins/slick.cellmenu.js, plugins/slick.contextmenu.js, plugins/slick.headermenu.js
- fixes #582
- the original issue only mentioned the HeaderMenu plugin but I went ahead and applied the same logic (and tested them all) on the following plugins
- HeaderMenu
- GridMenu
- ContextMenu
- CellMenu
=> fix: add preventDefault to optionally leave plugin menu open

plugins/slick.draggablegrouping.js, slick.grid.js
Although I have not reported the issue, I discovered a couple issues when freezing columns while column reordering is enabled.
1) The unfrozen column headers were disappearing  when I froze columns and had the pre-header row collapsed.
2) When columns were frozen dragging a column would make the unfrozen columns dissappear.
The commit message for the changes has details about the bugs and their causes.
These changes should be non-blocking and should improve behavior for frozen column support.
=> Fixes for issues with frozen columns,  column reordering, and preheader visibility

plugins/slick.cellrangeselector.js
Issue Description: if we have multiple grids in same page/in the DOM, earlier code looks for  '.grid-canvas-left' width which indeed gets the result of the grid where the event triggered along with the other grids present in the DOM. If the action is done on second grid(which has frozen column) instead of first one, earlier code is getting the width of first grid instead of second one. So made changes to get the width only for the event triggered grid.
=> To Fix the issue specific to drag selection in non-frozen part of grid if there are multiple grids.

slick.grid.js
- the available `target` options will be: "grid" or "composite"
- since we can also use the `onBeforeEditCell` event within the Composite Editor, I needed a way to make a distinction between a call made with `onBeforeEditCell` from the grid or from the composite component. This `target` will let me know where it was executed from.
=> feat: add target to `onBeforeEditCell`

slick.dataview.js, slick.grid.js
- since SlickGrid can be used in other libs and components, it could be useful to be more explicite from where the error originated, add SlickGrid prefixes to all error messages
=> feat: add better error message when throwing

slick.grid.js
1. Fix a typo in `getActiveViewportNode()`
```diff
function getActiveViewportNode(element) {
-      setActiveViewPortNode(element);
+      setActiveViewportNode(element);
```
2. Create function `getViewports()` to get `viewport` (Like `getCanvases()`)
```js
function getViewports() {
return $viewport;
}
```
3. Updata `getActiveViewportNode(columnIdOrIdx, rowIndex)` to get viewport by specified row and column. (Like `getCanvasNode(columnIdOrIdx, rowIndex)`)
=> fix: get viewport node by specified row and column like canvas

slick.core.js
it had errors thrown when using `autoEdit` and `setActiveCell` which calls `makeActiveCellNormal` which calls `deactivate` which finally throws that error even when the active edit controller is null but that shouldn't matter if it is already null then we shouldn't care and not throw
=> fix: deactivate edit controller shouldn't throw when active is null

slick.grid.js
- this new event will help in implementing a resize by cell content but only for the column that its resize was double-clicked (pretty much the same Excel)
- as shown in the print screen below, the event will trigger when we double-click while the resize icon shows up when hovering between 2 columns
=> feat: add onColumnsResizeDblClick event to adding new resize extras

slick.grid.js
- fixes #473
- with frozeen grid, we have 2 horizontal scrolling and if any of the column width on the left section goes over the viewport total width then we completely lose the scrolling on the right section (as described in issue #473)
- also note that the PR adds a new grid option `frozenRightViewportMinWidth` which is set to 100 by default and could be customized to a different minimum width for the right section of a frozen grid
=> fix: left frozen section shoudn't go over viewport width, fix #473

slick.grid.js
- if we change from a regular grid to a frozen grid dynamically by calling `setOptions({ frozenColumn: 2 })` then it should call `setOverflow` to redo the associated css overflow. This PR does just that and prior to this PR the overflow was just reset and sometime the scrolling was showing up on the left section when it shouldn't
@6pac after merging this PR, could you please do another version release since this bug has been affecting our users and I wish to close it once and for all. Thanks a lot 🍻
=> fix: `setOptions` should call `setOverflow` when changing frozenColumns

plugins/slick.state.js
until now it was not possible to reset the state. by adding the `reset` function to the `State` plugin, it's possible to reset the state by storing an empty object into `localStorage`.
=> Feature: Reset State

plugins/slick.rowmovemanager.js
- since `canMove` is a private property, we should make sure it's `true` before trying to execute the override, this problem was caught in our implementation because we do use the plugin with the usability override
=> fix(plugin): only check override if we can move row in first place

slick.dataview.js
- I need to know the filtered count and currently the only way I was able to do this was to get the entire array of filtered item to get its length which is not at all effective when we can simply add a 1 line function to its length :)
=> feat: add filtered item count

controls/slick.gridmenu.js
the default gridMenu button was a "must" until now. no way to disable it so that it wouldn't be printed (well, okay, yes, one could have probably used something like `display:none` in the css, but the button would still have been created nevertheless.
with this update, the button can be created or omitted by providing `showButton: false` in the option list. by default, this option is set to true, so the default behavior is not changed.
=> gridMenu button is now optional - default is on

slick.grid.js
- this bug is visible to the user when we try to build/load a grid from an hidden div (or a tab that is not active like below), what happens is that the Header Titles (header column) is shown behind the filter bar (header row) and to the user this seems broken. What happens is that the header height will be 0 and when that happens we can simply calculate it ourselves to avoid ever showing header without a height
see below, we load the page with active tab being the 1st tab, then if we go to 2nd tab (without the fix) we won't see the header titles... on the other end, with the fix, the header title bar will show up correctly
=> fix: broken UI when loading grid from hidden div/tab

slick.grid.js
- in our use case, we call a backend save but if the backend throws an error we want to undo the cell change, however there are no way to currently determine if the event is triggered by the execute or the undo. Simply put, the undo was also triggering a backend save which we of course don't want (especially so if the undo was because of a backend error thrown)
=> feat: add `command` (execute/undo) to `onCellChange` event

slick.grid.js
When my company tested the security of one of our applications, we found that we had missed to sanitize the values we send to Aurelia SlickGrid. We then also discovered that SlickGrid was not protected by the set Content Security Policy in the application, when script tags were run. After further investigation it turns out it's due to the jQuery function AppendTo being used. Which runs script tags automatically when they are appended. 
This PR does not replace all jQuery AppendTo, or for that matter fixes every places where CSP can not protect. It would been too much work for my company to put resources on, instead it only covers the part where we have dynamic data.
More information about this problem: 
https://csp.withgoogle.com/docs/faq.html#caveats …
=> Fix(slick.grid): Replace jQuery appendTo with js append for renderRows

plugins/slick.headermenu.js
- when the header menu is aligned to the right (instead of default to left), the menu was a bit offset because we were using the wrong width. 
now perfectly aligned to the right
=> fix: use Header Menu width (instead of minWidth) to align right

slick.grid.js
- for my use case, I need to execute some logic before the header menu are re-rendered by the `setColumns`
=> feat: add new event `onBeforeSetColumns`

plugins/slick.headermenu.js
- the `menu` variable can only have `items` since it comes from the column definition
=> fix: use tooltip from header menu options is the correct location

controls/slick.pager.js
until now, the paging options were fixed and could not be changed. meaning, it was not possible to add custom values to the pager. also, it was not possible to show the links to change the page size by default, i.e. they were always hidden by default. 
these changes would allow users to set their own `pagingOptions` and `showPageSizes`, respectively to define which page sizes should be shown and if the paging links are shown by default.
=> added custom paging options + configurable default show-page-sizes

slick.grid.js
There is an issue on firefox browser that prevent the user from making a selection.
This issue is already fixed in the original repository.
See https://github.com/mleibman/SlickGrid/pull/746/files
=> Fix for text selection in firefox

slick.grid.js
- in my use case, I want to cancel sort when backend server throws an error and to properly revert the sort, I need a reference to the previous sort
- this PR will make it possible to cancel sort and revert to previous sort as discussed on Slickgrid-Universal [here](https://github.com/ghiscoding/slickgrid-universal/discussions/337)
=> feat: add `previousSortColumns` to `onSort` and `onBeforeSort`

slick.dataview.js
- similar to previous commit #625 make the `onBeforePagingInfoChanged` cancellable so that user could prevent the event bubbling and cancel the action
- this is related this [Discussion](https://github.com/ghiscoding/slickgrid-universal/discussions/337) we started in Slickgrid-Universal
=> feat: make `onBeforePagingInfoChanged` cancellable

plugins/slick.checkboxselectcolumn.js
- if we use Row Selection with a grid that also has Grouping/Draggable Grouping, clicking on the "Select All" button would also include grouping rows and when calling DataView `getAllSelectedIds()` it would includes some `undefined` Ids which were found to be the grouping rows. So we should fix the issue at the source, which is to NOT include the grouping rows.
- the issue was reported in Slickgrid-Universal in this [comment](https://github.com/ghiscoding/slickgrid-universal/issues/469#issuecomment-913808526)
=> fix: grid with Grouping, Row Select All shouldn't include grouping rows

plugins/slick.state.js
in order to allow users to add their own extra data while saving grid's state, the `save` function is extended to allow userData
=> added the possibility to store `userData` while saving grid state

controls/slick.gridmenu.js, plugins/slick.cellmenu.js, plugins/slick.contextmenu.js, plugins/slick.headermenu.js
- make sure commands/options are defined and also allow `false` to work as it should
- also make the cellMenu/contextMenu work with just options set (without any commands)
=> fix: few minor fixes on plugin with menus

slick.grid.js
- Fixes #642 by not accessing rows' indices/fields if there are no rows.
- No errors in cypress tests on my machine
=> Getlongesttext handles empty rowset

plugins/slick.state.js
`state` will now only `scrollRowIntoView` if user wishes to
until now, restoring the state automatically brought the previously scrolled row into view (`scrollRowIntoView`) - from now on, the user has control over this function call.
**why?**
well, because this behavior caused issues with rendering the grid if the table was not initiated with any rows.
we have a grid whose lines are added/ updated from an async query, which might or might not change on every call. as the grid is initiated/created, there are initially no rows in it. calling this function when the grid has no rows causes a parameter in `slick.grid.js` (`th`) to be set to `NaN`, which then causes rendering issues - as shown below - when the rows were inserted into the grid. …
=> `scrollRowIntoView` is now only called if allowed by user

cypress/integration/example-frozen-columns-and-column-group.spec.js, cypress/integration/example-frozen-columns-and-rows.spec.js, cypress/integration/example-frozen-rows.spec.js, package-lock.json, package.json, slick.grid.js
- this PR fixes 2 issues identified in Frozen Grids and in Slickgrid-Universal lib
the grid shown below has both issues and this PR fixes both of them
1- the top portion of the grid below is broken and throws error shown below and is caused by a regression introduced via commit f12f4cc which is the new Post Async cleanup
2- the bottom portion, which shows `object` everywhere is caused by a regression introduced from previous PR #640
both issues can be seen in this live [Example](http://6pac.github.io/SlickGrid/examples/example-frozen-rows.html), the error thrown is 
```
Uncaught TypeError: Cannot read properties of null (reading 'removeChild')
```
which seems to be caused by `this.parentElement` being null in some cases
- [example-frozen-rows.html](https://6pac.github.io/SlickGrid/examples …
=> fix: regression introduced by PR #640 and commit f12f4cc

plugins/slick.cellcopymanager.js, slick.editors.js
$.ui.keyCode references have already been removed from other source files, but slick.editors and plugins/slick.cellcopymanager seem to have been missed.
Replaced these with Slick.keyCode values.
This removes the need to load jQuery UI (or an alternative $.ui implementation).
=> Replace remaining $.ui.keyCode references with Slick.keyCode

cypress/integration/example-composite-editor-modal-dialog.spec.js, cypress/integration/example-plugin-custom-tooltip.spec.js, examples/example-plugin-custom-tooltip.html, package-lock.json, plugins/slick.customTooltip.css, plugins/slick.customtooltip.js, slick.formatters.js, slick.grid.js
- display custom tooltip via a custom formatter, subscribes to `onMouseEnter` and `onMouseLeave` to create a Custom Tooltip
- also add 2x new events to work with header-row as well `onHeaderRowMouseEnter` and `onHeaderRowMouseLeave`
- requires to add 2x new events `onHeaderRowMouseEnter` and `onHeaderRowMouseLeave`
=> feat: add new Custom Tooltip plugin

examples/example-row-detail-selection-and-move.html, plugins/slick.rowmovemanager.js, slick.grid.css
- add option to create a simple clone of the row being moved and show it as a shadow (cloned element) of the row being moved so that we know exactly which row is being dragged (it follow the mouse cursor and once we stop moving it gets destroyed)
- also add options to change this shadow element opacity & scale size
- it's a simple feature but is very helpful to not lose track of exactly which row we're dragging
=> feat: show a shadow element of the row being moved/dragged

lib/jquery.event.drag-2.3.0.js
Check for data before setting the related property. This fixes an issue when using native DND in other components of our application. The error at the bottom is thrown at this line in `jquery.event.drag-2.3.0.js`:
```
remove: function(){
$.data( this, drag.datakey ).related -= 1;
},
```
=> jquery.event.drag check for data

cypress/integration/example-auto-scroll-when-dragging.spec.js, cypress/support/commands.js, cypress/support/common.js, cypress/support/drag.js, examples/example-auto-scroll-when-dragging.html, plugins/slick.cellrangeselector.js, plugins/slick.rowselectionmodel.js, slick.grid.js
(Related: https://github.com/6pac/SlickGrid/issues/114)
This PR allow auto scroll when dragging to make selection using `cellrangeselector`.
[Here is the example page](https://aasdkl.github.io/SlickGrid/examples/example-auto-scroll-when-dragging.html)
The scrolling speed is based on: `Math.max(MIN, MAX - DelayPerPx * cursorPx)`
I'm not sure that setting the option ON by default is appropriate or not.
---
Also, a cypress test is provided. But I'm afraid that these case may failed in some time because they have compared the dragging time interval:
- should MIN interval take effect when auto scroll: 30ms -> 90ms
- By default the MIN interval to show next cell is `30ms`.
- In the test I set the interval to `90ms` (3 times of the default).
- So ideally if we scrolling to same row by MIN …
=> feat: Auto scroll the viewport when dragging to make selection

plugins/slick.cellselectionmodel.js, plugins/slick.checkboxselectcolumn.js, plugins/slick.rowselectionmodel.js, slick.grid.js
- this is to cover a special use case that we have, in which the user can click a row which will possibly trigger other rows to be selected (in a Tree Data grid, we want to select all the children underneath), so we basically dynamically change row selection via `setSelectedRows` and the current code was problematic because internally SlickRowSelectionModel is also calling `setSelectedRows` and we have no way of knowing if the selection was made by the user or dynamically by the code, so this PR adds a `caller` property which tells us who really called the row selection.
- while at it, I also added extra properties, 3x in total: (`caller`, `changedSelectedRows` and `changedUnselectedRows`), this makes my code a lot cleaner since I often have to add extra code to know the last changes
Now …
=> feat: add extra caller property to onSelectedRowsChanged

controls/slick.gridmenu.js
So that menu can be hidden when user clicks somewhere else
=> export Slick.Controls.GridMenu.hideMenu()

examples/example-drag-row-between-grids.html, examples/example-row-detail-selection-and-move.html, examples/example9-row-reordering-simple.html, plugins/slick.cellrangeselector.js, plugins/slick.crossgridrowmovemanager.js, plugins/slick.rowmovemanager.js, plugins/slick.rowselectionmodel.js
The auto scroll behavious is added in this PR: https://github.com/6pac/SlickGrid/pull/656
Since it was modified on the `SelectionModel`,  it should be able to use with plugin `RowMoveManager` by some small fix:
```diff
+<script src="../plugins/slick.cellrangedecorator.js"></script>
-  grid.setSelectionModel(new Slick.RowSelectionModel());
+  grid.setSelectionModel(new Slick.RowSelectionModel({
+      cellRangeSelector: new Slick.CellRangeSelector({
+        selectionCss: {
+          "border": "none"
+        },
+      })
+  }));
```
However, when dragging on the row handler, the `RowSelectionModel` will be called before `RowMoveManager`, and the selected rows will be always be updated by `RowSelectionModel`.
To avoid the update, I extract the method `isHandlerColumn()` in …
=> bugfix: Apply auto scroll when dragging on RowMoveManager plugin

CODE_OF_CONDUCT.md
this is in reply to the last opened issue #676, it seems that this project is seriously missing a **Code of Conduct** document. 
Also consider this to be my last PR, enough is enough, there are ways to raise concerns and voice frustrations but the way that it was phrased in there is just not it. I must admit that I didn't read it all, I had enough after reading just half of it and then he double and triple-down. It wasn't the first time but it will be the last for me, I don't need this type of unconstructive and offensive language in my day to day life. I was planning to eventually work on removing jQueryUI but... I'm done and call it quit.
Here's a summary of my the few thousand of hours contributing to this lib for the past 5 years
- created the following plugins: 
- Auto-Resize, Cell …
=> docs: add missing Code of Conduct

slick.grid.js
When `fullWidthRows: true` is used in options, and when the viewport width is larger than the canvas width, slick grid does not create rows wide enough to fill the viewport.
This happens because although the total canvas width has been calculated to match that of viewport, the total canvas width is not distributed to the left/right canvas.
To illustrate:
**Without the fix and with this option: `{ fullWidthRows: true }`** , there is an area of white space at the right side of the canvas (selected row is colored in blue to make it more obvious):
**And with this option: `{ fullWidthRows: true,     frozenColumn: 2 }`**:
Basically visually the fullWidthRows has no effect.
**With the fix and with this option: `{ fullWidthRows: true }`**:
**Same for frozen columns `{ fullWidthRows: true, …
=> fix: adjust the left/right canvas width properly when fullWidthRows is used

plugins/slick.resizer.js
the setOptions function had a bug causing it to ignore previously set options if it was called a second time (i.e. each timer after `init`)
=> resolved an issue with resizer `setOptions` function

slick.grid.css
fixing this scss error
```
Fatal error: Error: Function rgb is missing argument $green.
on line 39 of my_project/css/style.scss
from line 1 of my_project/css/app.scss
>>   box-shadow: rgb(0 0 0 / 20%) 8px 2px 8px 4px, rgb(0 0 0 / 19%) 2px 2px 0px
--------------^
```
=> fixed rgba in box-shadow that causes scss error

examples/example-auto-scroll-when-dragging.html, examples/example-row-detail-selection-and-move.html, slick.grid.css
- removing jQueryUI CSS from the auto-scroll example made it stopped working, after troubleshooting section by section, it only seem to be caused by an extra border around the slickgrid header. We can copy over the same border from jQueryUI into SlickGrid CSS and auto-scroll works again :)
=> fix: auto-scroll should work even without jQueryUI

cypress/integration/example-composite-editor-modal-dialog.spec.js, examples/example-composite-editor-modal-dialog.html, slick.editors.js
- allows the user to enter a date directly into the input field. By default, direct entry is disabled.
- remove jQueryUI from Composite Editor example and also use Flatpickr editor, however for the Cypress E2E test to work, it is easier to type the date in the input instead of using Flapickr date & month in picker which is a lot harder to test with a script
=> fix(editors): allow input editing with Flatpickr editor

.github/workflows/main.yml, README.md
show a few useful badges on the readme page, mostly the npm version & CI build status
=> chore: add badge to show npm version and CI status

scripts/minify.js, scripts/release.js
- the versions used in the release were out of sync by a version, let's pass the same version to the minify process to avoid being out of sync
- for example looking at the last chore release [commit](https://github.com/6pac/SlickGrid/commit/ba6fc8eeab479813f1444637e01a29204a753ff0), we can see `package.json` is at "3.0.1" but all `dist/` files are at "3.0.0"
=> chore: provide same version to minify instead of reading from file

scripts/release.js
- release script should also update `slickGridVersion`, it seems like this was missed in original script.
- I have done a dry-run and it seems to be all good
=> chore: `slickGridVersion` property should also be updated in slick.grid

slick.grid.js
- add a delay of a cycle to avoid screen flickering that we observed to be worst in Chrome and Salesforce. This small delay of 1 cycle is enough to remove the flickering
- the process is that when the grid is being scrolled horizontally, it has to change the scroll position of every other div container that might exist (preheader, headerrow, footer) and if we change the position at the same time as the grid scroll it can cause flickering
- this flickering only happens in Chromium based browser (Firefox doesn't have this problem) and I'm pretty sure that last year we didn't have this problem so it might be a new Chrome bug (or Salesforce I don't know) but regardless of when, this PR should help in any case
- this PR should also help with this Stack Overflow …
=> fix: horizontal scrolling can cause screen flickering

cypress/integration/example-checkbox-header-row.spec.js, cypress/integration/example-row-detail-selection-and-move.spec.js, examples/example-checkbox-header-row.html, examples/example-row-detail-selection-and-move.html, plugins/slick.checkboxselectcolumn.js, slick.dataview.js, slick.grid.js
- supersede #689, most Grid & DataView changes were kept with some small changes & fixes, also added more Cypress E2E tests
- when having pages and `syncGridSelection` is called with `preserveHiddenOnSelectionChange`,  clicking on Select All checkbox:
- it will apply row selections on all rows
- if nothing is selected and we filter data, then we click on Select All, it will apply row selections only to the item being filtered and if we remove filters then the Select All  is not expect to be selected
- most of the files are the same (~`slick.grid.js`,~ `slick.checkboxselectcolumn.js`, `example-checkbox-header-row.html`), however `slick.dataview.js` got modified a bit
- added back `filteredIds` which was added originally but removed in PR #689
- the method `syncGridSelection` had a …
=> feat(dataView): add option to apply row selection to all pages

cypress/integration/example3-editing.spec.js, examples/example3-editing.html, slick.editors.js, slick.grid.js
- this new option is helpful when `autoEdit` is enabled, by default the `autoEdit` will automatically navigate down and automatically open the next row cell, however when `autoCommitEdit` is enabled it will save but not open the next row cell
- `autoEdit` after an editor save, will automatically change active cell to the next bottom cell editor and open it
- `autoCommitEdit` after an editor save, will stay in the same cell position and will **not** open the next row editor
Note:
I actually already have this feature in all my other SlickGrid libs since couple years but I was actually patching the issue by calling `commitCurrentEdit()` (which I also added in this PR) but then it was automatically navigating down, so what I was doing was to change again the cell position to the previous …
=> feat: add `autoCommitEdit` grid option

scripts/minify.js
- JS source map must be named the same as the original JS file + `.map` suffix, in our case since we have `.min.js`, we need the sourcemap to be named `.min.js.map` to be auto-detected but ours were named incorrectly as `.js.map` (missing `.min` prefix and cannot auto-detected by Chrome
=> fix: dist source map file naming was incorrect

plugins/slick.autotooltips.js
The current code does not show a tooltip when word wrap is turned on and the text is taller than the cell height.
=> show tooltip if the cell content is taller than the cell height - fixes #740

.eslintrc, slick.core.js, slick.dataview.js, slick.grid.js
- fixes some errors that came up while testing the whole thing in Slickgrid-Universal, with these changes all Slickgrid-Universal unit tests and demos are passing without jQuery in that lib
- these changes were requested in PR #734
- extends the previous PR #734, also note that more PRs will follow
=> fix: addresses all issues found in jQuery removal previous PR #734

examples/example-autotooltips.html, plugins/slick.autotooltips.js
- remove jQuery from plugin and also in the autotooltip example as well
=> feat(plugin): convert slick.autotooltips to vanillaJS

slick.core.js, slick.dataview.js
- Slick.Map polyfill is no longer required since Map is included in ES6 browsers
=> chore: remove Map polyfill since we will target ES6

slick.core.js, slick.interactions.js
- this fixes verbose warnings shown in Chrome and other browser console mentioning that we should consider using `passive` event listeners
- also uses a polyfill in case the `passive` option is not supported (for example IE)
- use `passive` event listener when possible for touch, mouse wheel, ... for better perf, see [SO](https://stackoverflow.com/a/37721906/1212166) and [MDN](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#improving_scrolling_performance_with_passive_listeners) details
=> fix(core): set wheel/touch listeners to passive for better perf

slick.core.js, slick.grid.js
- closes #667
- freezing columns cannot be wider than the actual grid canvas because when that happens, the viewport scroll becomes hidden behind the canvas... so let's throw an error advising the user to make adjustments
=> fix: throw error when freezing columns are wider than canvas

slick.core.js, slick.interactions.js
- rollback PR #769 that brough event passive mode, it turns out that all our SlickGrid events can use `preventDefault` which is what passive mode is for, so it's better to rollback all of it
console error caught while editing any cell on [example3-editing.html](https://6pac.github.io/SlickGrid/examples/example3-editing.html)
=> fix: rollback JS event passive mode in SlickGrid

slick.grid.js
- while testing in all other SlickGrid libs, I got the following console error thrown, so this PR fixes it by making sure all columns are defined before going further
> Cannot read properties of undefined (reading 'hidden')
and with these 2 PRs, I'm done with my libs testing, I'll be ready for an official release (that is after addressing the issues with hidden feature)
=> fix: make sure column is defined before calling hidden prop

plugins/slick.checkboxselectcolumn.js
- the checkbox row selection column should be excluded from all menus, defaults to true unless the option is provided differently by the user
- this was asked on Stack Overflow https://stackoverflow.com/questions/76424966/slickgrid-how-to-exclude-checkboxselectcolumn-from-columnpicker
=> feat: exclude checkbox selection from col picker/grid menu

examples/example-row-detail-selection-and-move.html
- example with 3 plugins was sorting with a column offset, the reason was because the RowMove plugin was created after SlickGrid and for that reason RowMove wasn't part of the columns passed to SlickGrid
- in short all plugins must change the `columns` array before passing it to the SlickGrid creation
=> fix(demo): example with 3 plugins not sorting correctly

controls/slick.gridmenu.js
- when removing frozen columns and then reapplying them, we might end up with 2 Grid Menu icons, we need to make sure to delete any previous grid menu icon before recreating a new one
after calling these 2 actions multiple times, we get 2x grid menu icons
as shown below
=> fix: Grid Menu is shown twice after changing frozen options

slick.grid.js
- some methods aren't supported in Salesforce for unknown reasons and it throws some errors like "append method does not exist", however they can be easily replaced. `.append()` can be replaced by `.appendChild()` and `.replaceChildren()` can be replaced with our own custom `.emptyElement()` that was already used in other areas
- similar to [commit](https://github.com/6pac/SlickGrid/commit/09dd7b39ffbf735db19e8068274120111d8b7140)
=> fix: replace some DOM Element functions not supported in Salesforce

slick.grid.js
- fixes an error detected in our Salesforce environment as shown below, the issue is simply that we should always make sure that we do have a valid DOM element before calling any method on that said element
=> fix: `getComputedStyle` could throw when DOM element is invalid

slick.core.js
- similar to the other PR I've opened but in a different method, we need to make sure that we have a valid DOM element before calling any method on that said element. In this case, the `parents()` function was throwing when trying to call `el.matches(...)` because the element was invalid
=> fix: make sure DOM element is valid before calling method on it

slick.grid.js
- the `onBeforeAppendCell` event can be used to return CSS classes as demoed in this [example2-formatters-event.html](http://6pac.github.io/SlickGrid/examples/example2-formatters-event.html), however when the user doesn't define or use this event then the event is always a `true` boolean that sometime gets added to the the `slick-cell` divs and that code was implemented that way from the beginning, we should really only use the event response when it is of type string but don't use it otherwise (because when the event is not defined or used by the user, its output will always be a `true` boolean and we don't want that to be added to our list of css classes)
- the original implementation was found in this old [commit](https://github.com/6pac/SlickGrid/commit/bef3203d722b96853a312929a74121ea …
=> fix: `onBeforeAppendCell` should only be used when it's a string

slick.grid.js
Hi team, 
I am using SlickGrid in my project and I have noticed that it is giving an unnecessary scrollbar when there's a single record in it and 2 empty pixels after the last row.
I have investigated the code and found that that while calculating the viewport height, the 2 pixels used for the **border** haven’t been considered. So, I have raised a PR for it.
**Before:**
This is the gird for single item. There is an unnecessary scrollbar and an unutilized 2px after the row.
_For multiple items._
Same here, unutilized 2px after the last row.
**After the fix:**
_For single row._
_For multiple items._
Thanks.
=> Viewport height fix

package.json, scripts/builds.mjs, scripts/dev-watch.mjs, src/plugins/slick.cellexternalcopymanager.ts, src/slick.core.ts, src/slick.grid.ts
- SlickCellExternalCopyManager was creating SlickRange with arguments in incorrect order
- add CJS build so that Slickgrid-Universal unit tests would work with Jest which requires CJS
=> chore: excel copy manager slickrange args was incorrect

src/slick.dataview.ts
- fixes 1 problem with `setFilter` identified in issue #848
- `setFilter` had the incorrect type, it should be `filterFn: (item: T, args: any) => boolean` and that is inline with what `filter` callback is defined on MDN https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter#parameters
- the first argument is the item being evaluated as per MDN: 
> The current element being processed in the array.
=> fix: DataView `setFilter` had incorrect type, partial fix #848

src/slick.grid.ts
- fixes #280
- when editing a cell and reordering a column OR changing the width of a column should refocus on the same active cell prior to the editing
- manually tested with result shown in animated gif below
=> fix: active cell loses focus after editing/column reordering, fix #280

examples/example16-row-detail.html, src/plugins/slick.rowdetailview.ts
- closes #378
user can now prevent event and return false on `onBeforeRowDetailToggle` event to cancel opening certain Row Detail, for example the code below would block opening Row Detail when its id is `1`
```ts
detailView.onBeforeRowDetailToggle.subscribe(function(e, args) {
// you coud cancel opening certain rows
if (args.item.id === 1) {
e.preventDefault();
return false;
}
console.log('before toggling row detail', args.item);
});
```
=> feat: add option to cancel Row Detail opening, closes #378

cypress/e2e/example-spreadsheet-dataview.cy.ts, cypress/e2e/example-spreadsheet.cy.ts, examples/example-spreadsheet-dataview.html, examples/example-spreadsheet.html, examples/index.html, src/plugins/slick.cellselectionmodel.ts, src/slick.grid.ts, src/styles/example-demo.scss
- fixes #794
- adding "pageUp/pageDown/home/end" to SlickCellSelection when using selection with "Shift+{key}"
- add `hasDataView()` and `getViewportRowCount()` methods to SlickGrid and also switch methods `getViewportHeight()` and `getViewportWidth()` from protected to public methods
- add new `example-spreadsheet-dataview.html` demo to manually test updated Cell Selection feature
=> feat: add pageUp/pageDown/home/end to SlickCellSelection, fixes #794

examples/example-excel-compatible-spreadsheet.html, src/models/gridOption.interface.ts, src/slick.grid.ts
- fixes #445
- when using CellExternalCopyManager and user wants to paste cell selection range, it could be useful to not automatically open the cell that was clicked even if it has an editor defined
=> fix: add `autoEditNewRow` option to disable auto-edit new row, fix #445

cypress/e2e/example-spreadsheet-dataview.cy.ts, cypress/e2e/example-spreadsheet.cy.ts, src/plugins/slick.cellselectionmodel.ts
- for better perf, we shouldn't have to recalculate page row count on every key change (i.e. clicking PageDown multiple times will remain the same row count displayed in the page), we can cache the row count and just reuse it
=> fix: CellSelectionModel calculate page row count only once

examples/example-drag-row-between-grids.html, examples/example-frozen-row-reordering.html, examples/example-row-detail-selection-and-move.html, examples/example9-row-reordering-simple.html, examples/example9-row-reordering.html, src/models/formatterResultObject.interface.ts, src/models/rowMoveManagerOption.interface.ts, src/plugins/slick.rowmovemanager.ts
- prior to this PR we only had a `cssClass` option but that was adding the CSS classes directly on the `.slick-cell` container and this was maybe ok before we added SlickGrid icons (SVG) but it's causing issue now as per attached printscreens. To address this, let's add a `cellContainerCssClass` that will keep "cell-reorder dnd" CSS classes on the cell container, but let's use the `cssClass` as a new `<div>` inside the slick-cell container, so this way our icon is totally separate from the slick-cell container and won't affect/conflict with its styling
in print screens below, we can see that the border under each Row Move (drag) icon is being removed for some reason, that was a styling conflict as described above
=> fix: add `containerCssClass` to RowMove to fix cell styling issue with icons

cypress/e2e/example-plugin-contextmenu.cy.ts, examples/example-plugin-contextmenu.html, src/models/cellMenuOption.interface.ts, src/models/contextMenuOption.interface.ts, src/models/menuCommandItem.interface.ts, src/models/menuItem.interface.ts, src/models/menuOptionItem.interface.ts, src/plugins/slick.cellmenu.ts, src/plugins/slick.contextmenu.ts, src/styles/slick.cellmenu.scss, src/styles/slick.contextmenu.scss
- also merge command/option code since we had a lot of duplicate code to do roughly the same thing but with different list (command/options)
- currently only works by `click` event on sub-menus, I tried to implement it with `mouseover`/`mouseout` but it's a lot more complex (we need to know if we are mousing over the correct sub-menu or over something else and this and that... wow just too much work)... so `click` should be enough for now, even though it's slightly less user friendly
- this is the 1st PR but in theory it should be easy enough to replicate for other menu plugins (GridMenu, HeaderMenu)
- i.e. Grouping does it in 2 ways: 1-add `slick-group-level-2` & 2-add `level="2"` attribute
=> feat: add sub-menu(s) to CellMenu & ContextMenu plugins

cypress/e2e/example-plugin-headermenu.cy.ts, examples/example-plugin-headermenu.html, src/models/headerMenuItems.interface.ts, src/models/headerMenuOption.interface.ts, src/plugins/slick.headermenu.ts, src/styles/slick.headermenu.scss
- currently only works by `click` event on sub-menus, I tried to implement it with `mouseover`/`mouseout` but it's a lot more complex (we need to know if we are mousing over the correct sub-menu or over something else and this and that... wow just too much work)... so `click` should be enough for now, even though it's slightly less user friendly
- build fails because `subMenuTitle` and `subMenuTitleCssClass` were added in previous PR
=> feat: add sub-menu(s) to HeaderMenu plugin

cypress/e2e/example-grid-menu.cy.ts, examples/example-grid-menu.html, src/controls/slick.gridmenu.ts, src/models/gridMenuCommandItemCallbackArgs.interface.ts, src/models/gridMenuItem.interface.ts, src/models/gridMenuOption.interface.ts, src/styles/slick.gridmenu.scss
- currently only works by `click` event on sub-menus, I tried to implement it with `mouseover`/`mouseout` but it's a lot more complex (we need to know if we are mousing over the correct sub-menu or over something else and this and that... wow just too much work)... so `click` should be enough for now, even though it's slightly less user friendly
- build fails because `subMenuTitle` and `subMenuTitleCssClass` were added in previous PR
=> feat: add sub-menu(s) to GridMenu control

cypress/e2e/example-grid-menu.cy.ts, examples/example-grid-menu.html, src/controls/slick.gridmenu.ts, src/models/gridMenuCommandItemCallbackArgs.interface.ts, src/models/gridMenuItem.interface.ts, src/models/gridMenuOption.interface.ts, src/models/menuCommandItem.interface.ts
- to align with other Menu plugins (ContextMenu, CellMenu), it's better if we rename `customItems` to `commandItems`, we'll only deprecate it for now so both names would work but the `customItems` will now show a console warning
=> fix: deprecate GridMenu `customItems` in favor of `commandItems`

cypress/e2e/example-grid-menu.cy.ts, cypress/e2e/example-plugin-contextmenu.cy.ts, cypress/e2e/example-plugin-headermenu.cy.ts, src/controls/slick.gridmenu.ts, src/models/cellMenuOption.interface.ts, src/models/contextMenuOption.interface.ts, src/models/gridMenuOption.interface.ts, src/models/headerMenuOption.interface.ts, src/plugins/slick.cellmenu.ts, src/plugins/slick.contextmenu.ts, src/plugins/slick.headermenu.ts
- when I implemented sub-menus, I thought it was complex to add open sub-menus via mouseover (not just click event) but it turns out to be quite easy with the latest code that was put in place for sub-menus. So this PR adds the mouseover option and does make it the default event (we have 2 options: `click` or `mouseover` and the latter is the default)
- this new mouseover will be the default but user could change it to work via click event only by changing the option to `subMenuOpenByEvent: 'click'` (instead of the default which is `subMenuOpenByEvent: 'mouseover'`)
=> feat: add `subMenuOpenByEvent` option to open sub-menus via mouseover

slick.grid.js
- add a flag `throwWhenFrozenNotAllViewable` that will now be set to `false` by default since this was causing issues in our environment, the flag can be set to `true` if any user want to add a try/catch and do other thing instead of simply throwing and leaving the grid in a non-functional state
=> fix: add `throwWhenFrozenNotAllViewable` grid option to avoid throwing

slick.grid.js
- there were many assumptions that certain objects/fields were defined and calls on them were being made but it could happen in certain rare case that these row cache fields are actually undefined and that threw errors on our end, so this PR adds more checks before using any of these row cache objects/arrays
=> fix: add more checks around cached rows

src/slick.grid.ts
=> fix: dynamically create CSS rules via JS instead of innerHTML

src/controls/slick.gridmenu.ts, src/models/core.interface.ts, src/plugins/slick.cellmenu.ts, src/plugins/slick.contextmenu.ts, src/plugins/slick.headermenu.ts, src/slick.core.ts
- when a sub-menu is closed, we remove it from the DOM but we also need to remove any click event listeners attached to all list items
=> fix: sub-menu event listeners leaking when closing sub-menus

cypress/e2e/example-colspan.cy.ts, cypress/e2e/example-csp-header.cy.ts, examples/example-csp-header.html, examples/example-csp-header.js, examples/example-csp-policy.js, examples/index.html, scripts/dev-watch.mjs, src/slick.core.ts, src/slick.grid.ts
- add CSP header example with trusted types
- to further improve CSP support for issue #878, we need to move `innerHTML` as separate assignment and not use it directly within a `createDomElement`, so for example this line `const elm = createDomElement('div', { innerHTML: '' })` should be split in 2 lines `const elm = createDomElement('div'); elm.innerHTML = '';`
=> chore: add CSP header example

cypress/integration/example-colspan.spec.js, cypress/integration/example-csp-header.spec.js, examples/example-csp-header.html, examples/example-csp-header.js, examples/index.html, slick.grid.js
backport PR #884 from master branch into version4 branch
=> chore: add CSP header example, backported from PR #884

slick.grid.js
- backported from PR #890 to support the creation of SlickGrid inside ShadowDOM
=> feat: add shadow dom support, backported from #890

slick.grid.js
- we can remove `.replaceChildren()` that is not supported in Salesforce (it basically doesn't like any functions targeting HTML Node instead of HTML Element), however we can simply replace the usage with our own `Utils.emptyElement(container);`
=> fix: element `replaceChildren()` not supported by salesforce

slick.grid.js, slick.interactions.js
- backported to v4.x from master branch PR #897
=> fix: add `allowDragFromClosest` to make `.slick-cell` or child draggable

slick.grid.js
- for some reason the new approach to use `const style = document.createElement('style')` and then `style.sheet` doesn't work in Salesforce, so let's add back the previous code as a fallback in case option 1 doesn't work
=> fix: create CSS rules by style element doesn't work in salesforce

src/slick.grid.ts
this fixes a bug reported in this Stack Overflow: https://stackoverflow.com/q/77408111/1212166
=> fix: misaligned column headers after horizontal scroll then freeze

slick.grid.js
=> fix: add `nonce` grid option set the nonce value for CSP header

examples/example-csp-header.html, examples/example-csp-header.js, src/models/gridOption.interface.ts, src/slick.grid.ts
* Made the user set the nonce value
- cherry-picked commit commit cb39c7a from PR #902 to merge into `master` branch
- however I had to put back previous CSP header since the master branch doesn't remove all `innerHTML` (which is in a separate draft PR)
=> fix: add `nonce` grid option set the nonce value for CSP header (#902)

package.json
- previous implementation didn't pass all type exports as can be shown in [Are the types wrong?](https://arethetypeswrong.github.io/?p=slickgrid) website, already applied the changes in `multiple-select-vanilla` library with a much greater success
- better approach came from RxJS [package.json](https://github.com/ReactiveX/rxjs/blob/master/packages/rxjs/package.json) which is a great implementation of it
=> fix: improve build & types exports for all targets, Node, CJS/ESM

cypress/e2e/example-auto-scroll-when-dragging.cy.ts, cypress/e2e/example-autotooltips.cy.ts, cypress/e2e/example-checkbox-header-row.cy.ts, cypress/e2e/example-checkbox-row-select.cy.ts, cypress/e2e/example-colspan.cy.ts, cypress/e2e/example-composite-editor-modal-dialog.cy.ts, cypress/e2e/example-csp-header.cy.ts, cypress/e2e/example-draggable-grouping.cy.ts, cypress/e2e/example-frozen-columns-and-column-group.cy.ts, cypress/e2e/example-frozen-columns-and-rows.cy.ts, cypress/e2e/example-frozen-rows.cy.ts, cypress/e2e/example-grouping-esm.cy.ts, cypress/e2e/example-grouping.cy.ts, cypress/e2e/example-plugin-custom-tooltip.cy.ts, cypress/e2e/example-row-detail-selection-and-move.cy.ts, cypress/e2e/example3-editing.cy.ts, cypress/e2e/example3b-editing-with-undo.cy.ts, cypress/support/commands.ts, examples/example-csp-header.html, examples/example-csp-header.js, examples/example-optimizing-dataview.html, src/slick.dataview.ts, src/slick.grid.ts
You can add 'useCSPSafeFilter: true' to the DataView options
=> fix: add CSP safe option for DataView filtering and adjusting inline css for CSP

src/controls/slick.columnmenu.ts, src/controls/slick.columnpicker.ts, src/controls/slick.gridmenu.ts, src/models/columnPicker.interface.ts, src/models/gridMenuOption.interface.ts, src/slick.dataview.ts, src/slick.grid.ts
- some interfaces were not fully updated in PR #894 which brought the possibility of passing HTMLElement to Formatter, then after updating these interfaces it was found that some controls/plugins did not handled the HTMLElement possibility
=> fix: interface for controls/plugins w/Formatter might return HTMLElement

cypress/e2e/example-example1-simple.cy.ts
- follow-up on PR #915 by widening the columns even more and making the scrolling slower to really make sure that we are testing the UI properly without using too much virtual scroll cache
=> chore: improve Cypress tests on basic grid w/large columns & scrolling

src/slick.interactions.ts
- the `onResize` was called twice, that was probably a copy+paste problem
- the event listener should be on `document.body` instead of just `document`
=> fix: interactions remove callback 2x call & add event listeners  to body

src/slick.interactions.ts
- the `onDragEnd` was called every time a cell was clicked even when user was not even dragging, we should make sure to only trigger `onDragEnd` if a drag actually started to avoid triggering too many events for no reasons
=> fix: Draggable shouldn't trigger dragEnd without first dragging

plugins/slick.cellrangeselector.js
- issue was found when user has an Editor open and then click on a row checkbox and start dragging that row checkbox cell, then the cell range decorator appears but never goes away because checkbox plugin has prevents event bubbling when having an editor and in turns wasn't destroying the cell range decorator when it should, the cell range decorator isn't visible but it has a z-index of 9999 and even though it's invisible it was showing on top of everything else making the cell behind it unclickable for the size of the cell range decorator (usually about the size of 2-3 cells)
=> fix(common): cell range decorator should be hidden after onDragEnd

src/slick.grid.ts, src/slick.groupitemmetadataprovider.ts
- in order to depend less on the use of `innerHTML`, we should convert internal code that have Formatter to use native HTML element to be more CSP compliant. However please note that the user will have to convert themselve the GroupTotals Formatter to native element as well for full CSP compliance on that section of the code
The code replaces the code shown below but using native HTML elements in a Formatter instead of HTML string
=> feat: convert GroupItemMetadataProvider Formatter to native HTML for CSP

src/slick.grid.ts
- when calling `applyHtmlCode` when a native element, we use `appendChild` but of course that will append to what already exist, however in the case of the util we should always clear the target element first since that is what we do when passing html string (assigning with `innerHTML` will overwrite any previous content)
- this was caught in one of the example when collapsing groups, we ended up seeing duplicate groups and this came up after converting SlickGroupItemMetadataProvider Formatter to return native element
=> fix: `applyHtmlCode` util should always clear targeted native element

src/models/cellRange.interface.ts, src/models/cssDeclaration.interface.ts, src/models/excelCopyBufferOption.interface.ts, src/models/externalCopyClipCommand.interface.ts, src/models/index.ts, src/plugins/slick.cellexternalcopymanager.ts, src/plugins/slick.cellrangedecorator.ts, src/plugins/slick.cellselectionmodel.ts, src/plugins/slick.rowselectionmodel.ts
=> fix: remove unused CellRange interface, use core SlickRange, fix #927

src/slick.core.ts, src/slick.grid.ts
- when calling `applyHtmlCode()` method and our target element is empty and we try to reapply empty, it should always be ok to simply skip this reassignment because the end result is exactly the same
- this should also help with performance since trying to reapply empty using `innerHTML` will probably cause a canvas repaint but if we manage to skip this assignment then a repaint will also be skipped
- it should help as well for CSP because we could write a Formatter with native element while still returning empty string when there's no value to return, that will then call `applyHtmlCode` and skip the assignment if the cell is already empty
for example the code below would be 100% CSP Safe and iinterpreted by SlickGrid as native without using `innerHTML` at all
```ts
function …
```
=> perf: skip reapplying empty html when target is already empty

slick.grid.js
- a previous PR #898 caused a regression on a cell with a select dropdown (like `Slick.Editors.YesNoSelect`), the regression was caused by the implementation of Draggable `allowDragFromClosest` which will check if current DOM element is `.slick-cell` or if not it will also try its parent and that caused the regression because the cell with the editor also had a `.slick-cell` and so the code taught that the user started a drag and it cancelled event bubbling which in turn also prevented the select dropdown to be clickable.
- to fix this issue we need to make sure that the cell is queried not just with `div.slick-cell` but also with certain CSS classes, we need to check if parent has either `.dnd` or `.cell-reorder` to permit the dragging when checking parent cell with …
=> fix: only allow row drag on cell w/`dnd` or `cell-reorder`

cypress/e2e/example-auto-scroll-when-dragging.cy.ts, cypress/e2e/example-spreadsheet-dataview.cy.ts, cypress/e2e/example-spreadsheet.cy.ts, cypress/support/commands.ts, cypress/support/drag.ts, examples/example-frozen-columns-and-rows-spreadsheet.html, examples/example-spreadsheet-dataview.html, examples/example-spreadsheet.html, src/plugins/slick.cellselectionmodel.ts, src/slick.grid.ts
the previous key combo were incorrect, the new combo is the following
- `Shift+Home` will select from current cell position to first cell horizontally
- `Shift+End` will select from current cell position until the last cell horizontally
- `Ctrl+Shift+Home` will select everything that is on the left side of current cell position and everything on top current position (horizontally left until first cell & vertically left until first row)
- `Ctrl+Shift+End` will select everything that is on the right side of current cell position and everything on bottom current position (horizontally right until last cell & vertically right until last row)
- fixes #935
The other key combos (with PageUp/PageDown/ArrowLeft/ArrowRight) remains the same
=> fix: revamp all cell selection range with key combos, fixes #935

src/slick.grid.ts
having a Formatter returning a number or boolean might not work correctly when passed to sanitizer like DOMPurify. We should simply apply text directly with `.textContent` without passing by the sanitizer
=> fix: calling `applyHtmlCode()` with number/boolean

src/plugins/slick.draggablegrouping.ts
- the drop box had a Sortable instance that was not destroyed causing it to not be garbage collected (mem leak)
=> fix: Draggable Grouping, destroy all Sortable instances fixes mem leak

slick.grid.js
as the title suggests this is meant to make unit/integration tests, e.g with testing-library, possible for apps using Slickgrid. In my specific case I'm making use of angular-slickgrid and would like to be able to test my app using angular-testing-library.
The introduced devMode workarounds are in order to work around the following jsdom issues:
* https://github.com/jsdom/jsdom/issues/2310 (missing clientWidth)
* https://github.com/jsdom/jsdom/issues/992 (missing ownerNode, even with a nice reference to Slickgrid ;) )
For additional conversations about this topic please refer to https://github.com/ghiscoding/Angular-Slickgrid/discussions/1319
P.S.: if this PR is fine I can later create an additional one targeting the master branch
=> feat: introduce devMode to support nodejs based unit testing

cypress/e2e/example-row-detail-selection-and-move.cy.ts, cypress/e2e/example16-row-detail.cy.ts, examples/example16-row-detail.html, src/models/formatterResultObject.interface.ts, src/plugins/slick.rowdetailview.ts, src/slick.core.ts, src/slick.grid.ts
with the CSP safe code implementation, the SlickRowDetail stopped working because it was using a hack. The hack was to using html string and add closing div tag to fall outside the `.slick-cell` but now that we use native HTML element then this hack no longer works. What we can do now is to add an optional `insertElementAfterTarget` that will provide a way to insert our Row Detail container element after our target which is this case is the `.slick-cell`
the issue was because we append everything into the `.slick-cell` HTML element inside it but SlickRowDetail was hacking the html string to insert the HTML element after the `.slick-cell`. So our new code will simply do it in the correct way via `insertElementAfterTarget`
we can see below, the `.dynamic-cell-detail` div is supposed to go …
=> fix: regression, Row Detail no longer displayed after CSP safe code

src/slick.grid.ts
- the previous code had 2 different `options` and `_options` that were not always in sync which caused issue when trying to update for example the `enableCellNavigation` option on the fly. With this new code change, there will no possibility to mix them up anywmore
=> fix: changing `enableCellNavigation` grid option not working

examples/example-frozen-columns.html, examples/example14-highlighting.html, src/models/gridOption.interface.ts, src/slick.grid.ts, src/styles/_variables.scss, src/styles/slick-alpine-theme.scss
- this new approach is much simpler than using ItemMetadata and calling multiple `updateItem()` and `render()` and is a lot more performant
- also fix potential mem leaks found on some `setTimeout` not having any `clearTimeout` assigned which could cause potential mem leaks
=> feat(core): add `rowHighlightCssClass` & `highlightRow()` to SlickGrid

src/slick.grid.ts
- the legacy TreeColumns depth was removed in PR #775 but some functions were missed and should be removed, they are `getHeadersWidthL()` and `getHeadersWidthR()` that are no longer referenced
=> chore: remove unused functions from legacy TreeColumns depth code

src/slick.groupitemmetadataprovider.ts
As it needs to be registered as plugin on grid to work properly, it should implement SlickGrid plugin interface, so typechecking of `grid.registerPlugin(groupItemMetadataProvider)` succeeds.
=> fix: GroupItemMetaDataProvider should implements SlickPlugin

src/models/grouping.interface.ts
Underlying slickgrid logic only takes into account equality between values returned for grouping individial rows. Getter thus does not need to return `string` but might return arbitrary value (e.g. string, number, Date).
Typing return value as `unknown` will force underlying logic using grouping getter to take into consideration that user might specify grouping function that returns arbitrary value type for individual row. With previous getter signature, user was forced to specify function that returned string, which is however not currenly needed by internal slickgrid logic.
=> fix: GroupingGetterFunction should be allowed to return arbitrary value

src/controls/slick.gridmenu.ts, src/plugins/slick.cellmenu.ts, src/plugins/slick.contextmenu.ts, src/plugins/slick.draggablegrouping.ts, src/plugins/slick.headerbuttons.ts, src/plugins/slick.headermenu.ts, src/slick.core.ts, src/slick.grid.ts
Extra spaces in `class` dom attribute are allowed in html (e.g. `class="some-class  other-class "`). SlickGrid should probably also behave the same way (or at least fail with some meaningfull validation error).
This commit just ignores all extra spaces in headerCssClass (between individual classes or leading / trailing).
I did not add E2E test for this, seems a bit overkill to add example html file for testing such minor case...
The error can be reproduced however by e.g. adding some space at the beginning / end of `headerCssClass` in `examples/example-web-component-pubsub-esm.html:193`
=> Allow extra spaces in headerCssClass

examples/example4-model-esm.html, src/models/function.type.ts, src/models/index.ts, src/slick.core.ts, src/slick.dataview.ts
- the sample code below, with inline ES6 arrow function, was not working prior to this PR
```ts
dataView = new Slick.Data.DataView({ inlineFilters: true });
dataView.setFilter((item, args) => item["percentComplete"] > args.percentCompleteThreshold);
```
=> fix: DataView `inlineFilters` should allow ES6 arrow functions

src/plugins/slick.cellselectionmodel.ts, src/plugins/slick.customtooltip.ts
It implied usage of SlickDataView which might provide paging; CustomDataView interface however does not require paging implementation. We assume that there is no paging on the dataview if getPagingInfo method not available on dataView.
=> fix: CellSelectionModel for CustomDataView and SlickCustomTooltip

src/controls/slick.columnmenu.ts, src/controls/slick.columnpicker.ts, src/models/core.interface.ts, src/models/gridEvents.interface.ts, src/plugins/slick.autotooltips.ts, src/plugins/slick.cellcopymanager.ts, src/plugins/slick.cellexternalcopymanager.ts, src/plugins/slick.cellmenu.ts, src/plugins/slick.cellrangeselector.ts, src/plugins/slick.cellselectionmodel.ts, src/plugins/slick.checkboxselectcolumn.ts, src/plugins/slick.contextmenu.ts, src/plugins/slick.crossgridrowmovemanager.ts, src/plugins/slick.customtooltip.ts, src/plugins/slick.headerbuttons.ts, src/plugins/slick.headermenu.ts, src/plugins/slick.rowdetailview.ts, src/plugins/slick.rowmovemanager.ts, src/slick.core.ts, src/slick.dataview.ts, src/slick.grid.ts, src/slick.groupitemmetadataprovider.ts
- fixes #967
- previously the 1st argument event was typed as `any` but in practical it will always be of type `SlickEventData` because a SlickEvent `.notify()` method always passes a SlickEventData
=> fix: EventHandler subscribed event should be SlickEventData type

src/models/core.interface.ts, src/models/rowDetailViewOption.interface.ts, src/plugins/slick.rowdetailview.ts, src/slick.core.ts
- continuation of previous PR #969 related to issue #967 to add proper types to SlickEventHandler arguments
=> fix(core): SlickEvent handler event should be type of ArgType

src/slick.grid.ts
- when we added SortableJS, we previously had code that is longer required since SortableJS already takes care of the order validation and such, there is also code related to Tree Column Depth that should have been removed.
- removed functions are: `currentPositionInHeader`, `remove`, `currentPositionInHeader` and `getImpactedColumns`
=> chore: remove unused code related to Column Reorder & SortableJS

cypress/e2e/example-checkbox-header-row.cy.ts, examples/example-checkbox-header-row.html, src/controls/slick.columnmenu.ts, src/controls/slick.columnpicker.ts, src/controls/slick.gridmenu.ts, src/models/column.interface.ts, src/models/columnPicker.interface.ts, src/models/excelCopyBufferOption.interface.ts, src/models/gridMenuOption.interface.ts, src/plugins/slick.autotooltips.ts, src/plugins/slick.cellexternalcopymanager.ts, src/plugins/slick.checkboxselectcolumn.ts, src/slick.core.ts, src/slick.grid.ts
- change Column interface `name` to also accept `DocumentFragment`
- change `headerColumnValueExtractor` to also accept `DocumentFragment`
- add `getHtmlStringOutput()` util to get HTML from any type of input (string, number, HTMLElement or DocumentFragment), which is especially useful with `DocumentFragment` which doesn't return HTML by default
- increase grid height in demo to fully test the checkbox count shown in current page (when using Pagination) in Cypress E2E tests
cc @JesperJakobsenCIM , I think (hope) this is the last piece to convert to native for CSP safe
=> feat: change CheckSelectColumn plugin to native HTML for CSP safe code

src/slick.grid.ts
- since we always assign `cell = 0` at the start, the `cell < -1` is technically unreachable, so there's no need to keep it
=> chore: remove `getCellFromPoint()` unreachable code

src/slick.grid.ts
- this PR replicates an old SlickGrid PR (except the focus which can cause other issues) https://github.com/mleibman/SlickGrid/pull/616 
- it also adds the `tabIndex: -1` on the cell which was mentioned in the issue and it seems to work the same as Ag-Grid does, with keyboard navigation so it looks ok to me
- fixes #518 (but maybe just partially, I'm not sure since I'm a newbie with these accessibility stuff and nobody wants to help much so... pushing this PR and closing the ref issue)
=> fix: add grid & cell `role` for screen ready accessibility, fixes #518

src/slick.grid.ts
- the previous code was skipping hidden columns, however we have a `widths` array that relies on column index and it became out of sync when a hidden column is skipped because the indexes no longer matches the column widths indexes when it is used in the next for loop
=> fix: legacyAutosizeColumns should push hidden width as 0

examples/example4-model-esm.html, src/slick.interactions.ts
- when `onResizeStart` returns `false`, for example when editor `commitCurrentEdit()` fails, then the column resize shouldn't be allowed
https://github.com/6pac/SlickGrid/blob/ab634eb0b1c83542c5e6ac75f84e16fa02510609/src/slick.grid.ts#L1939-L1943
=> fix: when `onResizeStart` return false it should stop

src/slick.interactions.ts
- when `onDragInit` returns `false` then the row or cell dragging shouldn't be allowed
- this is similar to previous PR #978
=> fix: when `onDragInit` return false it should stop

src/plugins/slick.cellselectionmodel.ts, src/plugins/slick.rowselectionmodel.ts
- a regression was introduced when dropping jQuery, the SlickEvent structure changed in the `notify` function. Previously a SlickEvent would accept a CustomEvent directly and the previous code was expecting that event to exists and override its CustomEvent `detail`, however the newer approach is to always use a SlickEventData and no longer use the CustomEvent directly and this caused the regression since the SlickEventData doesn't have a `detail` property but rather something like this `SlickEventData { event: { detail } }`
- the fix is to simply create a CustomEvent with `{ detail: caller }` which we then pass to the `SlickEventData` constructor so that our `caller` isn't lost and rather reused later when triggered by `onSelectedRowsChanged`
=> fix: regression `onSelectedRowsChanged` not receiving correct `caller`

examples/example14-highlighting.html, src/models/gridOption.interface.ts, src/slick.core.ts, src/slick.grid.ts
- also rework some code using `classNameToList()` util, we can permit any amount of spaces to css classes like Formatter `addClasses`
- also cleanup and simplify some code around other css classes, `classNameToList` returns an array of string and we can take advantage of iterator available in DOM `classList.add()` and `.remove()`
=> fix: add missing option to control row highlight duration

src/slick.groupitemmetadataprovider.ts
```(bool ? obj.f1 : obj.f2)(params)``` is an antipattern as ```obj``` is not passed as ```this``` to the function
=> fix example error

src/plugins/slick.rowdetailview.ts, src/slick.grid.ts
- as mentioned in this [Stack Overflow](https://stackoverflow.com/a/43446317/1212166), `Object.keys().forEach` are quicker than `for..in` because the latter also loops through prototype chain.
=> perf(core): convert `for..in` to `Object.keys().forEach` for better perf

.github/workflows/main.yml, cypress/e2e/example-trading-esm.cy.ts, cypress/e2e/example4-model.cy.ts, examples/example-trading-esm.html
- Grouping wasn't working and was caused by a duplicate DataView instantiation and the 2nd one didn't have the groupItemMetadataProvider and it was basically overriding the 1st one which was the correct one with the groupItemMetadataProvider plugin instantiated which is needed for the Grouping to work correctly
=> fix: realtime trading demo grouping wasn't working

src/models/column.interface.ts, src/models/editor.interface.ts, src/models/editorArguments.interface.ts, src/models/gridOption.interface.ts, src/slick.grid.ts
editor and edtitor factory do not return an Editor Object but a typeof Editor to be constructed with new (...) Otherwise it is impossible to implement an Editor Factory in Typescript
=> fix: `column.editor` and `gridOptions.editorFactory` type changed

.eslintrc, src/models/autoSize.interface.ts, src/models/editorValidator.interface.ts, src/models/grouping.interface.ts, src/models/interactions.interface.ts, src/models/slickPlugin.interface.ts, src/plugins/slick.cellcopymanager.ts, src/plugins/slick.cellrangedecorator.ts, src/plugins/slick.crossgridrowmovemanager.ts, src/plugins/slick.rowmovemanager.ts, src/slick.dataview.ts
for more info, read this ESLint article: https://typescript-eslint.io/blog/consistent-type-imports-and-exports-why-and-how/
=> fix: add ESLint-TS rules to enforce `type` imports and exports

.eslintrc, package-lock.json, package.json
- the original `eslint-plugin-node` is no longer maintained, so let's migrate to the suggested alternative `eslint-plugin-n`
=> chore: migrate from eslint-plugin-node to `eslint-plugin-n`

src/models/editor.interface.ts, src/slick.grid.ts
The 'keyCaptureList' variable of the Editor class is an array of numbers.
=> fix: Editor.keyCaptureList is an array of numbers

src/models/editorValidator.interface.ts, src/slick.editors.ts
When I try to apply default SlickGrid Editors to the 'editor' field of the Column object I receive TypeScript error.
I'm not sure that I did everything correctly, I just want to contribute and save your time. Review my changes please.
=> fix: SlickGrid editors are not assignable to column field 'editor'

src/slick.dataview.ts
It would be very handy for developers to have ability to receive extra arguments of filter function. For example when filter is applyed we can: 
- write a custom date editor which can suggest a year for user, relying on the selected year filter;
- fill cell values automatically when adding a new row, otherwise the row will not be displayed;
- and much more.
Previously there was ability to receive extra arguments of filter function by using `dataView.filters` property and much featers have already been written by using it. Now we need a way to keep these features working.
=> feat: add the ability to receive extra filter arguments

package.json
It's written in the `package.json` file that primary entry point has path `"./dist/browser/index.js"`, but there is no such file there.
Although library works when I try to run integration tests with Jest for files which make import from node_module 'slickgrid' it complains `Cannot find module 'slickgrid'`
=> fix: primary entry point to the program isn't set correctly

cypress/e2e/example-excel-compatible-spreadsheet.cy.ts, cypress/support/commands.ts, cypress/tsconfig.json, package-lock.json, package.json, src/plugins/slick.cellexternalcopymanager.ts
When using doing copy-paste with CellExternalCopyManager, the grid loses focus after Ctrl-V.
The issue can be seen on [example-excel-compatible-spreadsheet](https://6pac.github.io/SlickGrid/examples/example-excel-compatible-spreadsheet.html) by playing with the arrow keys and doing some copy/paste.
The commit reuses the code found some 20 lines before in the same function to restore the focus.
=> Fix: CellExternalCopyManager plugin restores focus on paste

src/slick.grid.ts
one line change, fixes this issue [comment](https://github.com/6pac/SlickGrid/issues/603#issuecomment-2043954473)
=> FIX: Remove ForceFit deprecation message, fixes #603

src/slick.grid.ts
Tweak setupColumnSort() to fix exception when a no longer existing column is in the sort list. 
Fixes #1015
=> Fix: Tweak setupColumnSort() to fix exception when col no longer exists

examples/example-frozen-columns-and-column-group-hidden-col.html, examples/example-frozen-columns-and-column-group.html, src/controls/slick.gridmenu.ts, src/models/gridMenuOption.interface.ts, src/styles/slick.gridmenu.scss
- add `iconButtonContainer: 'preheader' | 'header'` grid option (default to `'header'`). For example, the Grid Menu is shown in the Draggable Grouping drop zone but it should really be in the Column Header section, we'll change the default to `'header'` but let's add a grid option to let the user choose either `'preheader'` or `'header'`
=> feat: add `iconButtonContainer` option to Grid Menu

src/models/gridOption.interface.ts, src/models/interactions.interface.ts, src/slick.grid.ts, src/slick.interactions.ts
- the issue was brought by a user and the root cause was the mouse drag sometime kicks in when the user selects a few row by using the Ctrl+click combo, however in rare occasion the user might move by even a single pixel and that sends an onDrag event which the SlickCellRangeSelector picks up when then sends a new event `onCellRangeSelecting` and then the SlickRowSelectionModel assumes it's a new range from a mouse drag and override the previous range. However we should really prevent this mouse drag from happening when the user is pressing the Ctrl/Shift keys to avoid having the issue that was brought
=> feat: add new `preventDragFromKeys` grid option

src/models/gridOption.interface.ts, src/slick.grid.ts
- add a new `preHeaderPanelWidth` grid option and set it to `auto` to take full width but without being wider than its actual container
=> fix: Draggable Grouping drop zone in preheader should take full width

cypress/e2e/example-draggable-header-grouping.cy.ts, examples/example-draggable-header-grouping.html, examples/index.html, src/models/gridOption.interface.ts, src/plugins/slick.draggablegrouping.ts, src/slick.grid.ts, src/styles/slick-alpine-theme.scss, src/styles/slick-default-theme.scss
- prior to this PR, we could not use Draggable Grouping & Header Grouping because both features were using the pre-header and it would have conflict, now to avoid this I am adding an extra Top-Header that will show over all header and pre-header.
- NOTE: Draggable Grouping can now be displayed in either the new Top-Header OR the Pre-Header. However, the users who do want to use both features will need to explicitely enable both top/pre headers.
- I was getting a little out of ideas to get a name (since "pre" is already taken), so I decided to go with Top-Header which is completely on the top and even before the pre-header. 
- Another note is that this new Top-Header is not following the frozen columns (like header & pre-header do) and is rather always the same width as the grid. I …
=> feat: add optional Top-Header for Drag Grouping + Header Grouping

cypress/e2e/example-draggable-header-grouping.cy.ts, cypress/e2e/example-frozen-columns-and-column-group.cy.ts, examples/example-column-group.html, examples/example-draggable-header-grouping.html, examples/example-frozen-columns-and-column-group-hidden-col.html, examples/example-frozen-columns-and-column-group.html, src/controls/slick.columnpicker.ts, src/models/gridEvents.interface.ts, src/slick.core.ts, src/slick.grid.ts
- adding new events `onPreHeaderContextMenu` and `onPreHeaderClick` which is mostly to be able to open the Column Picker from either the regular column headers OR the Column Group from the Pre-Header when defined
- also works with/without frozen column
- fixed some examples where the preheader weren't recalculated after reordering columns or hiding columns from picker
=> feat: add onPreHeaderContextMenu for Column Picker usage

src/slick.grid.ts, src/styles/_variables.scss, src/styles/slick-alpine-theme.scss
- also while at it, let's fix some alignment issues with menu items as well
=> fix: Column Header Menu should be on top of grid not inside

src/slick.grid.ts
https://github.com/6pac/SlickGrid/issues/1038#issuecomment-2246829300
=> Fixed an issue where pinning the first column caused the header to get misaligned

src/models/column.interface.ts, src/slick.editors.ts
Add a generic `params` in Column interface so that user can provide extra and untyped options, for example `params.editorOptions` to add extra settings to some Editors like the Flatpickr date format
For example 
```
columns = [
{
id: "finish", name: "Finish", field: "finish", 
editor: Editors.Flatpickr, 
params: { editorOptions: {altFormat: 'Y-m-d', dateFormat: 'Y-m-d'}}, 
]
```
=> feat: add `params.editorOptions` to change Flatpickr Editor date format

src/models/gridOption.interface.ts, src/slick.grid.ts
- see this [comment](https://github.com/6pac/SlickGrid/issues/219#issuecomment-1630077429) for more info
- a lower thottling delay (5ms instead of previously 50ms) will show blank area for a much shorter period whenever we scroll to an uncached scroll position (for example completely scroll to bottom of large grid)
- NOTE: a throttling of 0ms causes flickering and/or other issues in some cases, but 5ms seems like a good number to use
=> perf: decrease virtual scroll render throttling to 5ms

cypress/e2e/example-frozen-rows.cy.ts, cypress/e2e/example-grouping-esm.cy.ts, examples/example-frozen-rows.html, examples/example-grouping-esm.html, examples/example-grouping.html, src/models/gridOption.interface.ts, src/slick.grid.ts
- related to issue #1044, provide a new grid option to allow the possibility to use top offset CSS style via `transform` instead of `top` to fix some UI rendering issue on large dataset
- this might improve perf as well as per this article: [Why Moving Elements With Translate() Is Better Than Pos:abs Top/left](https://www.paulirish.com/2012/why-moving-elements-with-translate-is-better-than-posabs-topleft/)
- we could possibly make this the default in our next `major` release (if it ever happen) but for now we can at least provide it as a new grid option. I also tested this with the Example Grouping (ESM) demo
=> perf: add new `rowTopOffsetRenderType` grid option to use "transform"

src/plugins/slick.cellexternalcopymanager.ts, src/slick.grid.ts
- prior to this PR, the hidden columns were being counted as column indexes when pasting and also when starting a cell selection
=> fix: SlickCellExternalCopyManager should work w/hidden cols

src/slick.dataview.ts
- Optimize getAllSelectedFilteredItems and preSelectedRowIdsChangeFn with Set lookup and reducing time complexity from O(n square) to O(n)
=> perf: Reduce iterative time complexity in DataView

src/controls/slick.columnpicker.ts
- similar to auto-positioning of Header Menu, we can auto-position left/right Column Picker with viewport available space
=> fix: reposition column picker to always be visible

src/plugins/slick.cellexternalcopymanager.ts
fixes #1078 
- using SlickExternalCopyManager plugin shouldn't change scroll position when copy/pasting values in the grid
=> fix: ExternalCopyManager shouldn't change body scroll pos, fixes #1078

scripts/changelog.mjs, scripts/fs-utils.mjs
we can do this function with plain `node:fs` code
=> chore: remove unnecessary fs-util function

cypress/e2e/example-frozen-columns-and-rows-spreadsheet.cy.ts, cypress/e2e/example-spreadsheet-dataview.cy.ts, cypress/e2e/example-spreadsheet.cy.ts, examples/example-frozen-columns-and-rows-spreadsheet.html, src/plugins/slick.cellselectionmodel.ts, src/slick.grid.ts
- add a few missing key shortcuts to navigate in the grid
- Ctrl+Home will now go to top left (coord 0, 0)
- Ctrl+End will now go to bottom right of the grid
- add a few missing key shortcuts for cell selection
- Shift+Ctrl+ArrowLeft, now same as Shift+Home, to select cells from current cell until starting index on same row
- Shift+Ctrl+ArrowRight, now same as Shift+End, to select cells from current cell until end index on same row
- Shift+Ctrl+ArrowUp to select cells from current cell up to first row on same column
- Shift+Ctrl+ArrowDown to select cells from current cell down to last row on same column
- Ctrl+a (or A) to select all cells in the grid
=> fix: add missing key shortcuts for grid navigation & cell selections

src/slick.grid.ts
- certain nav commands are navigating away from current viewport and when re-navigating back to another cell that is in the same viewport (like 0,0 with Ctrl+Home) then it sometimes has 2 active cells instead of never more than 1.
- this can probably occur a little more after recent PR #1093
=> fix: remove "active" CSS classes before navigating to another cell

src/models/groupItemMetadataProviderOption.interface.ts, src/slick.dataview.ts, src/slick.groupitemmetadataprovider.ts
- allow providing a custom global item metadata provider by passing it through the `groupItemMetadataProvider` DataView constructor option
- implementation copied from https://github.com/GerHobbelt/SlickGrid fork
=> feat: add Custom Global Item Data Provider, closes #262

src/slick.grid.ts
- it seems that PR #1095  was always enough
=> fix: never activate more than 1 cell, clear any previous active class

src/plugins/slick.draggablegrouping.ts, src/slick.grid.ts
- we should add the CSS class `slick-column-header-active` to the Header Cell **only** when we start dragging that header, otherwise we shouldn't and that wasn't the case before which showed a the active header and a flickering especially in Dark Mode
=> fix: opening Header Menu shouldn't add Active Header Cell

cypress/e2e/example-0031-row-span-employees.cy.ts, examples/example-0031-row-span-employees.html, examples/index.html, src/slick.grid.ts
fixes #1114
expose `remapAllColumnsRowSpan()` function publicly since a full remap is sometime necessary when column indexes need to be fully remapped.
=> fix: expose `remapAllColumnsRowSpan()` to fix #1114

src/plugins/slick.cellselectionmodel.ts
As per Slickgrid-Universal [PR](https://github.com/ghiscoding/slickgrid-universal/pull/1880)
> it seems we introduced a bug back in the December release where SHIFT + A inside an editor would perform a cell selection instead of writing the capital A letter.
> You can try it out on https://ghiscoding.github.io/Angular-Slickgrid/#/editor, editing a Country of Origin Name cell and trying to type SHIFT + A.
=> fix: shift + a should not select all cells upwards

cypress/e2e/example-checkbox-row-select.cy.ts, src/models/gridEvents.interface.ts, src/plugins/slick.checkboxselectcolumn.ts, src/slick.grid.ts
fixes #1119
- Select All disappears whenever reordering a column to another position because again it called the grid set columns and that again rerendered all column headers without the Select All
- to fix issue, I added a new `onAfterSetColumns` SlickEvent which we subscribe to inside the SlickCheckboxSelectColumn plugin, and whenever triggered, we reevaluate the Select All which in term recreates it
=> fix: Select All checkbox shouldn't disappear w/column toggle, fix #1119

examples/example-frozen-columns-autoheight.html, src/slick.grid.ts
fixes #1122 
- when preHeader is enabled, it should be added to the calculation of the grid container auto-height, this wasn't the case before and the frozen scroll ended up being shown in the hidden section making it completely unusable
=> fix: autoHeight should add preHeader height when enabled, fixes #1122

src/slick.grid.ts
related to Slickgrid-Universal [issue](https://github.com/ghiscoding/slickgrid-universal/issues/2034)
=> fix: change to stopPropagation to avoid browser scrolling

src/plugins/slick.customtooltip.ts
this PR makes sure that the toggling of the title and data-slick-tooltip attributes of the customTooltip plugin only happens if there is a value to set.
=> fix: only toggle title and data-slick-tooltip if value is defined

src/plugins/slick.cellrangeselector.ts, src/slick.interactions.ts
- when grid has RowMove enabled and user starts dragging with auto-scroll but releases the mouse when outside the body viewport, the `mouseup` event was never triggering because we were falling outside the `document.body` which was the event registered. We can simply register the `mouseup` on `window` instead of `document.body` so that it would still get triggered even if the user is outside the document body/viewport. This will avoid the issue reported in the comment above and demoed below.
=> fix: auto-scroll outside the viewport should stop Row Move dragging

src/models/cellRange.interface.ts, src/plugins/slick.cellrangedecorator.ts
Add second range selector css property to allow visual difference in selection between initial select and drag-expand select.
=> feat: Add second css property to RangeDecorator plugin
